### ISSUE TITLE
where can i find c3d pytorch model

### ISSUE THREAD

**Issue by 1senlin** [ekosman/AnomalyDetectionCVPR2018-Pytorch#1]
hi，i goole c3d pytorch，but i can not find this ，can you give a link to download this ，thanku very much～～

**Comment by ekosman** [comment]
@1senlin see [here](https://github.com/csuhuihui/pytorch-c3d)

**Comment by nitincs** [comment]
http://imagelab.ing.unimore.it/files/c3d_pytorch/c3d.pickle

**Comment by ekosman** [comment]
@nitincs Can I put a link to this model in README?

**Comment by nitincs** [comment]
https://github.com/DavideA/c3d-pytorch/blob/master/README.md

@https://github.com/DavideA/c3d-pytorch

**Comment by nitincs** [comment]
@ekosman , i am trying to work this out for my project, can we connect through hangouts? ns22@iitbbs.ac.in

**Comment by 1senlin** [comment]
> @1senlin see [here](https://github.com/csuhuihui/pytorch-c3d)

thanku very much , i have another question, where can i test the videos and get the result if it is Anomaly , thanks ~~

**Comment by 1senlin** [comment]
> @nitincs Can I put a link to this model in README?

thanku very much , i have another question, where can i test the videos and get the result if it is Anomaly , thanks ~~

**Comment by ekosman** [comment]
@1senlin I didn't create a script for this, but this should be super easy, but I'm very busy now

If anyone can write it and contribute, that would be very helpful :)

**Comment by 1senlin** [comment]
> @1senlin I didn't create a script for this, but this should be super easy, but I'm very busy now
> 
> If anyone can write it and contribute, that would be very helpful :)

**Comment by 1senlin** [comment]
> > @1senlin I didn't create a script for this, but this should be super easy, but I'm very busy now
> > If anyone can write it and contribute, that would be very helpful :)

thanks ,i did not write this before, but i am very interested in this work.. thanku very much

**Comment by 1senlin** [comment]
> @1senlin I didn't create a script for this, but this should be super easy, but I'm very busy now
> 
> If anyone can write it and contribute, that would be very helpful :)

hi, bother you again，i get the result of one video,i found that the result is not very good , i want to know if the model trained not well?

**Comment by 1senlin** [comment]
The result is very volatile

**Comment by ekosman** [comment]
@1senlin for testing if your model is trained well, generate the ROC and see if you get the expected results

**Comment by 1senlin** [comment]
python feature_extractor.py --dataset_path "path-to-dataset" --annotation_path "path-to-train-annos" --annotation_path_test "path-to-test-annos" --pretrained_3d "path-to-pretrained-c3d"

i download c3d model ,and do this 
but have this error 
no corresponding:: conv1.weight
no corresponding:: conv1.bias
no corresponding:: conv2.weight
no corresponding:: conv2.bias
no corresponding:: conv3a.weight
no corresponding:: conv3a.bias
no corresponding:: conv3b.weight
no corresponding:: conv3b.bias
no corresponding:: conv4a.weight
no corresponding:: conv4a.bias
no corresponding:: conv4b.weight
no corresponding:: conv4b.bias
no corresponding:: conv5a.weight
no corresponding:: conv5a.bias
no corresponding:: conv5b.weight
no corresponding:: conv5b.bias
no corresponding:: fc6.weight
no corresponding:: fc6.bias
no corresponding:: fc7.weight
no corresponding:: fc7.bias
no corresponding:: fc8.weight
no corresponding:: fc8.bias

**Comment by haoranD** [comment]
> python feature_extractor.py --dataset_path "path-to-dataset" --annotation_path "path-to-train-annos" --annotation_path_test "path-to-test-annos" --pretrained_3d "path-to-pretrained-c3d"
> 
> i download c3d model ,and do this
> but have this error
> no corresponding:: conv1.weight
> no corresponding:: conv1.bias
> no corresponding:: conv2.weight
> no corresponding:: conv2.bias
> no corresponding:: conv3a.weight
> no corresponding:: conv3a.bias
> no corresponding:: conv3b.weight
> no corresponding:: conv3b.bias
> no corresponding:: conv4a.weight
> no corresponding:: conv4a.bias
> no corresponding:: conv4b.weight
> no corresponding:: conv4b.bias
> no corresponding:: conv5a.weight
> no corresponding:: conv5a.bias
> no corresponding:: conv5b.weight
> no corresponding:: conv5b.bias
> no corresponding:: fc6.weight
> no corresponding:: fc6.bias
> no corresponding:: fc7.weight
> no corresponding:: fc7.bias
> no corresponding:: fc8.weight
> no corresponding:: fc8.bias

hi, did you successfully use the C3D to extract the features? I got the same error as yours. Can you please give me some advice?

**Comment by haoranD** [comment]
> python feature_extractor.py --dataset_path "path-to-dataset" --annotation_path "path-to-train-annos" --annotation_path_test "path-to-test-annos" --pretrained_3d "path-to-pretrained-c3d"
> 
> i download c3d model ,and do this
> but have this error
> no corresponding:: conv1.weight
> no corresponding:: conv1.bias
> no corresponding:: conv2.weight
> no corresponding:: conv2.bias
> no corresponding:: conv3a.weight
> no corresponding:: conv3a.bias
> no corresponding:: conv3b.weight
> no corresponding:: conv3b.bias
> no corresponding:: conv4a.weight
> no corresponding:: conv4a.bias
> no corresponding:: conv4b.weight
> no corresponding:: conv4b.bias
> no corresponding:: conv5a.weight
> no corresponding:: conv5a.bias
> no corresponding:: conv5b.weight
> no corresponding:: conv5b.bias
> no corresponding:: fc6.weight
> no corresponding:: fc6.bias
> no corresponding:: fc7.weight
> no corresponding:: fc7.bias
> no corresponding:: fc8.weight
> no corresponding:: fc8.bias

Hi, I solved this problem. Did you successfully extract the features, because I think the VideoClips function costs massive memory.

**Comment by libb999** [comment]
> > python feature_extractor.py --dataset_path "path-to-dataset" --annotation_path "path-to-train-annos" --annotation_path_test "path-to-test-annos" --pretrained_3d "path-to-pretrained-c3d"
> > i download c3d model ,and do this
> > but have this error
> > no corresponding:: conv1.weight
> > no corresponding:: conv1.bias
> > no corresponding:: conv2.weight
> > no corresponding:: conv2.bias
> > no corresponding:: conv3a.weight
> > no corresponding:: conv3a.bias
> > no corresponding:: conv3b.weight
> > no corresponding:: conv3b.bias
> > no corresponding:: conv4a.weight
> > no corresponding:: conv4a.bias
> > no corresponding:: conv4b.weight
> > no corresponding:: conv4b.bias
> > no corresponding:: conv5a.weight
> > no corresponding:: conv5a.bias
> > no corresponding:: conv5b.weight
> > no corresponding:: conv5b.bias
> > no corresponding:: fc6.weight
> > no corresponding:: fc6.bias
> > no corresponding:: fc7.weight
> > no corresponding:: fc7.bias
> > no corresponding:: fc8.weight
> > no corresponding:: fc8.bias
> 
> Hi, I solved this problem. Did you successfully extract the features, because I think the VideoClips function costs massive memory.

hi  i meet the same problem, can you tell me how to solve it ?
thank you very much!

**Comment by PHDPeter** [comment]
I think I have sold this by using the below code.
I think this is a problem from python 2 to python 3?
        for name in p_dict:
            if name not in corresp_name.values():
                print("no corresponding::", name)
                continue

            #print("s_dict "+str(s_dict))
            #print(name)
            #print("p_dict[name] "+str(name))
            #corresp_name[name]
            #key=get_key(name, corresp_name)
            #corresp_name[name]
            s_dict[name] = p_dict[name]
        self.load_state_dict(s_dict)

I get a comment at the end showing:
no corresponding:: fc7.weight
no corresponding:: fc7.bias
no corresponding:: fc8.weight
no corresponding:: fc8.bias

but these are not show in the corresp_name so I am assuming are not needed here?

**Comment by PHDPeter** [comment]
> I think I have sold this by using the below code.
> I think this is a problem from python 2 to python 3?
> 
> ```
>     for name in p_dict:
>         if name not in corresp_name.values():
>             print("no corresponding::", name)
>             continue
>         s_dict[name] = p_dict[name]
>     self.load_state_dict(s_dict)
> ```
> 
> I get a comment at the end showing:
> no corresponding:: fc7.weight
> no corresponding:: fc7.bias
> no corresponding:: fc8.weight
> no corresponding:: fc8.bias
> 
> but these are not show in the corresp_name so I am assuming are not needed here?

@ekosman is that correct?

**Comment by ekosman** [comment]
@PHDPeter ignore this, the paper uses fc6 of C3D as embedding, thus fc7 and fc8 aren't needed

**Comment by PHDPeter** [comment]
Thank for that @ekosman

**Comment by wzy1845** [comment]
> I think I have sold this by using the below code.
> I think this is a problem from python 2 to python 3?
> 
> ```
>     for name in p_dict:
>         if name not in corresp_name.values():
>             print("no corresponding::", name)
>             continue
>         s_dict[name] = p_dict[name]
>     self.load_state_dict(s_dict)
> ```
> 
> I get a comment at the end showing:
> no corresponding:: fc7.weight
> no corresponding:: fc7.bias
> no corresponding:: fc8.weight
> no corresponding:: fc8.bias
> 
> but these are not shown in the corresp_name so I am assuming are not needed here?

hi, I encountered a similar problem.. After a long string of "no corresponding" (conv1 to fc8), feature _extractor.py only extracts the features of 24 videos, while I put the whole dataset in dataset_path. Which part should I add to the code you provided? Any help or points for the issue would be greatly appreciated，thanks！

**Comment by ekosman** [comment]
Hi @wzy1845 
I just added some code to ignore unused layers in c3d. You should not see this errors anymore:
```python
no corresponding:: fc7.weight
no corresponding:: fc7.bias
no corresponding:: fc8.weight
no corresponding:: fc8.bias
```

However, if you see other errors (corresponding to other layers), maybe the c3d file is wrong.

**Comment by wzy1845** [comment]
> Hi @wzy1845
> I just added some code to ignore unused layers in c3d. You should not see this errors anymore:
> 
> ```python
> no corresponding:: fc7.weight
> no corresponding:: fc7.bias
> no corresponding:: fc8.weight
> no corresponding:: fc8.bias
> ```
> 
> However, if you see other errors (corresponding to other layers), maybe the c3d file is wrong.
> 
> Also, I refactored the code for `data_loader`. Let me know if it all good now.

Thank you very much for helping. The error of "no corresponding" no longer appears, but I still can't extract the features of all videos in the dataset, as shown below. Is there anything I did wrong? I do not know how to solve it. TAT. Thank you very much!
![IMG_20200511_173915](https://user-images.githubusercontent.com/58544419/81568434-5b273c00-93d0-11ea-81ff-00686754efa0.jpg)
![IMG_20200511_173924](https://user-images.githubusercontent.com/58544419/81568442-5ebac300-93d0-11ea-8677-0c27d3407086.jpg)

**Comment by PHDPeter** [comment]
This could be related to error I am looking at right now (https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/20)

**Comment by wzy1845** [comment]
> This could be related to error I am looking at right now (#20)

hi, thanks for helping. I try your way (by changing the video_idx to idx ) and can get the features of all videos in the dataset now, but the features look very strange (the second half of each txt file contains only zero)，and the ROC is terrible. Do you have a similar situation? Or other suggestions? Thank you very much!

**Comment by PHDPeter** [comment]
Yeah, looks like it was not that simple a fix.
Mind chatting about this on the https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/20 issue? keep it all in one place :-)

**Comment by ekosman** [comment]
Merged a branch that fixes this
