### ISSUE TITLE
Problem about feature extraction

### ISSUE THREAD

**Issue by pengjinqiang** [ekosman/AnomalyDetectionCVPR2018-Pytorch#100]
Hi，thanks for your excellent work. 
It seems that you use pre trained C3D from [https://github.com/DavideA/c3d-pytorch](url) to extract the UCF-crime video feature. But the C3D model is pre trained on Sport1M. Does that make sense to use the C3D model pre trained on Sport1M to extract the UCF-crime video feature?
Thanks!

**Comment by ekosman** [comment]
@pengjinqiang 
The paper states that it uses the default settings for C3D but doesn't specify which pretrained model to use.
As far as I checked, the original implementation uses the caffe version trained on sport-1m, and therefore I used this one too. However, it'd be interesting to see if using a different pretrained model affects the results.

**Comment by pengjinqiang** [comment]
> @pengjinqiang
> The paper states that it uses the default settings for C3D but doesn't specify which pretrained model to use.
> As far as I checked, the original implementation uses the caffe version trained on sport-1m, and therefore I used this one too. However, it'd be interesting to see if using a different pretrained model affects the results.

My opinion is that, suppose I want to extract UCF-crime video feature, should I use UCF-crime as a recognition task to train C3D, then I use the C3D model pre trained on UCF-crime to extract UCF-crime video feature? Is this necessary? Or will that help to extract better video feature?

**Comment by ekosman** [comment]
That is an interesting experiment. However, I can't find any pretrained C3D model on UCF-crime I can use for feature extraction.

Also, the benefit of using this pretrained model is not definite.
