### ISSUE TITLE
issue about AD_live_prediction

### ISSUE THREAD

**Issue by Chuttyboy** [ekosman/AnomalyDetectionCVPR2018-Pytorch#102]
Hello @PHDPeter @ekosman 

issue: `Import "annotation_methods" could not be resolved`

line number: 271

thank you

**Comment by ekosman** [comment]
In which file?

**Comment by ekosman** [comment]
Hi @Chuttyboy 

I fixed this script. Let me know if this is solved. I will close this on 31/12 if there are no further issues.
