### ISSUE TITLE
How can i test on new videos?

### ISSUE THREAD

**Issue by aaalanj** [ekosman/AnomalyDetectionCVPR2018-Pytorch#11]
Dear author, i find that compared with original version, there isn't a file similar to Test_Anomaly_Detector_public.py ,so how can i test the performance on a new video?
Looking forward to your answer!

**Comment by ekosman** [comment]
I didn't create an individual script for that.
Unfortunately, I don't have access to the envoironment where I developed this project so I can't write and test this right now. However, it shouldn't take much effort so feel free to write and contribute :)

**Comment by PHDPeter** [comment]
I am working on this (#16) which should do what you want thou you would need a pertained wights to run with it.
I will make sure to put in a pull request when I have this "live_GUI" working :-)
