### ISSUE TITLE
Invalid link to pretrained C3D weights

### ISSUE THREAD

**Issue by ldjmgls** [ekosman/AnomalyDetectionCVPR2018-Pytorch#112]
Hi @ekosman ,

The download link to C3D weights in https://github.com/DavideA/c3d-pytorch is invalid.
Do you know other sources where the weights can be downloaded?

Thank you!

**Comment by ekosman** [comment]
@ldjmgls Hi
The link works for me. Could you check again?

**Comment by ldjmgls** [comment]
<img width="859" alt="Pasted Graphic 1 copy" src="https://user-images.githubusercontent.com/43908497/163263010-d21422a0-dd1f-4dc1-a90d-c1879c88b629.png">

I still can download the model by clicking **here** or http://imagelab.ing.unimore.it/files/c3d_pytorch/c3d.pickle.

**Comment by ekosman** [comment]
Then, it seems that the link is valid. Right?

**Comment by ldjmgls** [comment]
Ooh, sorry typo. I mean "still cannot download" the model by clicking **here** or http://imagelab.ing.unimore.it/files/c3d_pytorch/c3d.pickle.

**Comment by ekosman** [comment]
Can you elaborate? For me, the link works just fine.
