### ISSUE TITLE
Video not Displayed

### ISSUE THREAD

**Issue by SanketPathak7** [ekosman/AnomalyDetectionCVPR2018-Pytorch#113]
At my end I'm selecting a video from the Anomaly video player, It is getting extracted and I'm getting predictions but it's not getting played, for this I checked the video duration, it is 0 sec. Also when the clip_length is set to 16 by default it throws Assertion error: Torchsize. Can you please throw some light on the same? Running it on Windows 10.

**Comment by jesung1221** [comment]
https://clay-atlas.com/us/blog/2020/10/14/pyqt5-en-qmediaplayer-directshowplayerservice/
Maybe this would help?

**Comment by ekosman** [comment]
Sorry for the late response. I'm quite busy lately. Could you share the video here, so that I can reproduce the error?

**Comment by ekosman** [comment]
Closed because the error is not reproducible. Also, please make sure that the video file you use is valid, e.g. its duration is not zero.
