### ISSUE TITLE
Error during video demo

### ISSUE THREAD

**Issue by jesung1221** [ekosman/AnomalyDetectionCVPR2018-Pytorch#115]
I am encountering the following error, while playing Abuse001_x264.mp4. What could be a fix for the following error?
 (It works for other video like Arson005)
![image](https://user-images.githubusercontent.com/13336580/168427569-6be97926-6206-4b3f-9520-29a3ad5c6c10.png)

**Comment by ekosman** [comment]
Could you share the video here, so that I can reproduce the error?

**Comment by Mayao15** [comment]
> 

The video mentioned is a video in the UCF_Crime dataset.  You can find it in UCF_Crime/videos/Abuse or download it from the link:
https://1drv.ms/v/s!AqCREq0NjbXnrbBxED-Mic6czellUA?e=ODITDK

**Comment by Mayao15** [comment]
> Could you share the video here, so that I can reproduce the error?

The video mentioned is a video in the UCF_Crime dataset. You can find it in UCF_Crime/videos/Abuse or download it from the link:
https://1drv.ms/v/s!AqCREq0NjbXnrbBxED-Mic6czellUA?e=ODITDK

**Comment by Mayao15** [comment]
Maybe this can help you 
https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/116#issuecomment-1140047699

**Comment by ekosman** [comment]
Hi, sorry for the great delay. For me this works just fine:

![תמונה](https://user-images.githubusercontent.com/10260165/174442197-a8a1c5de-d388-4ceb-8634-7efeeaaabc3b.png)

**Comment by ekosman** [comment]
@jesung1221 Let me know if you experience any other issues. Otherwise, I'll close this on 30/6. Thanks.
