### ISSUE TITLE
AssertionError: torch.Size([17, 240, 320, 3]) x 16   

### ISSUE THREAD

**Issue by jesung1221** [ekosman/AnomalyDetectionCVPR2018-Pytorch#116]
I am using Abuse001_x264.mp4 from the UCF-Crime dataset as an input.
I am facing this Assertion Error?
Is there a specific dimension requirement for the input videos?
![image](https://user-images.githubusercontent.com/13336580/170432925-a6ad68a5-b84d-434c-8a4b-2707d02b794e.png)

**Comment by jesung1221** [comment]
The following error can be fixed by commenting out 
\lib\site-packages\torchvision\datasets\video_utils.py
line 369
assert len(video) == self.num_frames, f"{video.shape} x {self.num_frames}

By doing so, the AssertionError will not be called

**Comment by Jimmycreative** [comment]
hi I wonder how can i access \lib\site-packages\torchvision\datasets\video_utils.py and comment this line out?
