### ISSUE TITLE
Error while running video_demo.py

### ISSUE THREAD

**Issue by imPdhar** [ekosman/AnomalyDetectionCVPR2018-Pytorch#117]
Ran the command ``python video_demo.py --feature_extractor "exps/resnet_r3d101_KM_200ep/models/epoch_10.pt" --feature_method "c3d" --ad_model "exps/c3d/models/epoch_80000.pt" --n_segments "32" `` but got error TypeError: 'AnomayDetector' object is not iterable. Not sure why this is happening. Can someone help me? 
Attaching screenshot for reference.

![Screenshot 2022-05-31 110622](https://user-images.githubusercontent.com/37359679/171100707-80e71056-cedb-41e4-8722-aaeb23d43587.png)

**Comment by Peggy118** [comment]
@imPdhar  Hi, sorry for bothering you. I met the same error. Did you solve this problem?

**Comment by imPdhar** [comment]
> @imPdhar Hi, sorry for bothering you. I met the same error. Did you solve this problem?

I unfortunately did not.
