### ISSUE TITLE
Need Help in test_annotation.txt

### ISSUE THREAD

**Issue by rabaig** [ekosman/AnomalyDetectionCVPR2018-Pytorch#120]
> The numbers indicates the range of frames where anomalies occure. 30 90 -1 -1 means anomaly between frames 30-90. -1 -1 means no second anomaly in the video.
> 
> Notice that all normal video are annotated with -1 -1 -1 -1, thus no anomalies in these videos. All anomaly videos have at least one pair (and at most two pairs) of numbers, indicating the frames range.

Hello @ekosman ,

I would like to append my custom videos to the UCF-Crime dataset. I have successfully done feature extraction and could you help how to make custom annotation for train and test dataset.
For train, I have added custom features path in Train_annotation.txt
could you help me how to make test_annotation.txt

Thanks
Rafi

_Originally posted by @rabaig in https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/18#issuecomment-1152560475_

**Comment by ekosman** [comment]
@rabaig What kind of help do you need?

**Comment by rabaig** [comment]
@ekosman  I have some custom videos and I would like to train and test its anomaly.

I need help to create its annotations files.

One way I thought is to append to existing train and test annotations files. I successfully extracted features.

when I see train_annotation.txt  1st line --> Vandalism/Vandalism048_x264.mp4 7183 .    Could you tell me what does that 7183 means ?

Also I would like to create test_annotations.txt for my custom videos 

RoadAccidents/RoadAccidents021_x264.mp4 155 RoadAccidents 30 90 -1 -1  -- for this you explained in the previous issue that 30 and 90 is the frame range that anomoly occurs . what about 155 how does it get created?

So, to make it very simple how does you suggest me to create train and test annotations files for my custom videos

Thanks & Regards
rafi

**Comment by ekosman** [comment]
> when I see train_annotation.txt 1st line --> Vandalism/Vandalism048_x264.mp4 7183 . Could you tell me what does that 7183 means ?

As I just took these annotations from the original repo, the code doesn't make use of it. You can just append random numbers there.



> RoadAccidents/RoadAccidents021_x264.mp4 155 RoadAccidents 30 90 -1 -1 -- for this you explained in the previous issue that 30 and 90 is the frame range that anomoly occurs. what about 155 how does it get created?

155 stands for the length of the video.

**Comment by ekosman** [comment]
Anything else @rabaig ?

If not, I will close this issue by 10/7/2022.

**Comment by ekosman** [comment]
@rabaig Sorry, I'm not aware of a simplified method of creating annotations. You may contact the original authors of the paper, maybe they have insights.

**Comment by rabaig** [comment]
Thanks for the support. I will try seeking help from original author. You can close this issue.

**Comment by ekosman** [comment]
@rabaig Happy to help! :)
