### ISSUE TITLE
The problem of enumerate

### ISSUE THREAD

**Issue by bingma03** [ekosman/AnomalyDetectionCVPR2018-Pytorch#13]
Hi,
I got a problem when I extracted features. It happened in the mathod of enumerate(train_iter) in the file of feature_extractor.py. Do you know how to sove this problem? Thank you!
![image](https://user-images.githubusercontent.com/31856259/72071942-e069e980-3327-11ea-8768-ff0d18c50e31.png)

**Comment by bingma03** [comment]
> Hi,
> I got a problem when I extracted features. It happened in the mathod of enumerate(train_iter) in the file of feature_extractor.py. Do you know how to sove this problem? Thank you!
> ![image](https://user-images.githubusercontent.com/31856259/72071942-e069e980-3327-11ea-8768-ff0d18c50e31.png)

This problem has been solved. I removed the set class before returning vid_list in the fuction of get_video_list.

**Comment by G-Morgen** [comment]
Hi，
I have the same problem. Can you tell me how you solved it?@bingma03

**Comment by bingma03** [comment]
> Hi，
> I have the same problem. Can you tell me how you solved it?@bingma03

I removed the set method.
![image](https://user-images.githubusercontent.com/31856259/72143583-ecaa8100-33d1-11ea-9f46-6dd7ecba722a.png)

**Comment by G-Morgen** [comment]
> > Hi，
> > I have the same problem. Can you tell me how you solved it?@bingma03
> 
> I removed the set method.
> ![image](https://user-images.githubusercontent.com/31856259/72143583-ecaa8100-33d1-11ea-9f46-6dd7ecba722a.png.


Hi,
Thank you very much, Can we have more communication？Could you add my QQ or Wechat?
QQ:121080986

**Comment by ekosman** [comment]
Removing the set seems to be the right way to fix this. I originally added it because I used a bad annotations file which contained duplicates, thus 'set' removed it.
