### ISSUE TITLE
Error: "Your GStreamer installation is missing a plug-in."

### ISSUE THREAD

**Issue by Dev-ori** [ekosman/AnomalyDetectionCVPR2018-Pytorch#132]
Hi, I have this issue when running "video_demo.py " can somebody help? 

I've already tried below, but didn't work.

1. "sudo apt install ubuntu-restricted-extras' 
2. sudo apt install gstreamer1.0-plugins-good/bad/ugly
3. pip install pyqt5

OS:
Linux-5.4.0-121-generic-x86_64-with-debian-buster-sid'

Warning: "No decoder available for type 'video/x-h264, variant=(string)itu, framerate=(fraction)25/1, width=(int)4096, height=(int)2160, interlace-mode=(string)progressive, chroma-format=(string)4:2:0, bit-depth-luma=(uint)8, bit-depth-chroma=(uint)8, parsed=(boolean)true, stream-format=(string)avc, alignment=(string)au, profile=(string)high, level=(string)5.1, codec_data=(buffer)01640033ffe1001a67640033acd940100010fa1000000300100000030320f183196001000668ebe3cb22c0'."
Error: "Your GStreamer installation is missing a plug-in."

**Comment by ekosman** [comment]
Interesting. Unfortunately, I don't know how this can be solved. Can you try this proposal?

https://stackoverflow.com/questions/39607522/no-decoder-available-for-type-video-x-h264

Let me know if you find a solution, so I can update the FAQ.
