### ISSUE TITLE
regarding - On-line (via webcam)

### ISSUE THREAD

**Issue by Chuttyboy** [ekosman/AnomalyDetectionCVPR2018-Pytorch#133]
Hai @ekosman 

My project is related to this topic ( Anomaly detection ). After successful completion of training, how can I test the model with live anomaly prediction? 

thanks

**Comment by ekosman** [comment]
Hi @Chuttyboy ,
Have you tried using `video_demo.py`?

**Comment by Chuttyboy** [comment]
Hai @ekosman

Yes, I tried `AD_live_prediction.py`. But it takes more time to extract frames.

Thanks

**Comment by suki1504** [comment]
@ekosman @PHDPeter 

`[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video0): can't open camera by index`

I am facing this error while running the below command 

`python AD_live_prediction.py --feature_extractor c3d.pickle --feature_method c3d` 
                    `--ad_model exps/c3d/models/epoch_80000.pt --clip_length 32`

How to resolve that ???

Thanks

**Comment by ekosman** [comment]
> @ekosman @PHDPeter
> 
> `[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video0): can't open camera by index`
> 
> I am facing this error while running the below command
> 
> `python AD_live_prediction.py --feature_extractor c3d.pickle --feature_method c3d` `--ad_model exps/c3d/models/epoch_80000.pt --clip_length 32`
> 
> How to resolve that ???
> 
> Thanks

Hi @suki1504 
I tried to run the same command and it worked for me. Can you please try again with the current code version?
