### ISSUE TITLE
Not able to Reproduce AUC of 0.8 in the Experiments with C3D Features of UCF-Crime

### ISSUE THREAD

**Issue by santiagosilas** [ekosman/AnomalyDetectionCVPR2018-Pytorch#135]
**Not able to Reproduce AUC of 0.8 in the Experiments with C3D Features of UCF-Crime**

I achieve an AUC = 0.71 on the test-set. The README file reports and AUC of 0.8. 
Could you provide the model which obtains this AUC value ?

**Comment by ekosman** [comment]
Which models are you using? I think these results were achieved using `r3d152`.

**Comment by ekosman** [comment]
@santiagosilas 

FYI, I updated README with the relevant information. You can re-open this issue if there is any other problem.
