### ISSUE TITLE
Run Video_demo from extracted feature, not by feature extractor

### ISSUE THREAD

**Issue by Dev-ori** [ekosman/AnomalyDetectionCVPR2018-Pytorch#136]
Hi, :) 

I'm trying to running 'video_demo.py'
**Not using the 'Feature extractor', but using 'extracted features'** 

Because I want to implement i3d to your project, BUT I only have I3D-extracted-UCF-Crime-features(.npy files by clip) 

So, in conclude, I want to try following methods.

"Skip the feature extractor and feature method argument in the 'video_demo.py' and just give them extracted feature and ad_model."

Is there any suggestion or guideline to modify the code to do that?
or Is it could be even possible ?

**Comment by ekosman** [comment]
This is possible. It would require calling a dedicated function in line 238 of `video_demo.py`, instead of calling `features_extraction`.

**Comment by ekosman** [comment]
@Dev-ori 

I added this new feature now. You can simply load a feature file after you load a video:
![תמונה](https://user-images.githubusercontent.com/10260165/208172716-b671c780-9001-4bab-86ec-8a2d15b550d8.png)
![תמונה](https://user-images.githubusercontent.com/10260165/208172776-097677ff-53f2-444e-a266-96650023b868.png)
![תמונה](https://user-images.githubusercontent.com/10260165/208172879-d0b59518-25f2-479c-97fc-887669286e1a.png)
![תמונה](https://user-images.githubusercontent.com/10260165/208172930-da74f762-9901-445e-9665-d68f3666962e.png)
![תמונה](https://user-images.githubusercontent.com/10260165/208172970-95615665-3603-45e0-99e2-f84dfa762460.png)


Enjoy!

**Comment by Dev-ori** [comment]
> @Dev-ori
> 
> I added this new feature now. You can simply load a feature file after you load a video: ![תמונה](https://user-images.githubusercontent.com/10260165/208172716-b671c780-9001-4bab-86ec-8a2d15b550d8.png) ![תמונה](https://user-images.githubusercontent.com/10260165/208172776-097677ff-53f2-444e-a266-96650023b868.png) ![תמונה](https://user-images.githubusercontent.com/10260165/208172879-d0b59518-25f2-479c-97fc-887669286e1a.png) ![תמונה](https://user-images.githubusercontent.com/10260165/208172930-da74f762-9901-445e-9665-d68f3666962e.png) ![תמונה](https://user-images.githubusercontent.com/10260165/208172970-95615665-3603-45e0-99e2-f84dfa762460.png)
> 
> Enjoy!

This is awesome ! Santa .
good luck!
