### ISSUE TITLE
Doubt in Train_Annotation.txt

### ISSUE THREAD

**Issue by prasaddev9** [ekosman/AnomalyDetectionCVPR2018-Pytorch#148]
Could you provide me the "pretrained_3d path" in "feature_extractor.py" of both c3d and i3d? 
![Screenshot from 2022-12-30 17-26-47](https://user-images.githubusercontent.com/108169138/210068068-b2abbc8e-86a5-4785-86c2-64904dafde70.png)

**Comment by ekosman** [comment]
I3D is not supported yet. C3D weights are available in the README.

**Comment by prasaddev9** [comment]
Thanks @ekosman. 

I am trying to implement I3D network. After implementation, I'll share with you. 

Btw I am having a doubt in "Train_Annotation.txt". 

![Screenshot from 2023-01-04 08-29-30](https://user-images.githubusercontent.com/108169138/210476605-9af6ee7f-67c6-4801-94bc-33f036281054.jpg)

1. What does it signifies in second column of each annotation file of Train_Annotation.txt [Screenshot attached] ?

2. Also how can we create our own annotation ?

**Comment by ekosman** [comment]
They mean the length of the video. You can just append random numbers there. As I just took these annotations from the original repo, the code doesn't make use of it.

Thanks for asking. I will clarify this in the README.

> Thanks @ekosman.
> 
> I am trying to implement I3D network. After implementation, I'll share the code with you.
> 
> Btw I am having a doubt in "Train_Annotation.txt".
> 
> ![Screenshot from 2023-01-04 08-29-30](https://user-images.githubusercontent.com/108169138/210476605-9af6ee7f-67c6-4801-94bc-33f036281054.jpg)
> 
>     1. What does it signifies in second column of each annotation file of Train_Annotation.txt [Screenshot attached] ?
> 
>     2. Also how can we create our own annotation ?

**Comment by ekosman** [comment]
Unless there are further questions, I'll close this issue by 15/1
