### ISSUE TITLE
FeaturesWriter/read_features format has chnaged? (.txt or .pickle)

### ISSUE THREAD

**Issue by PHDPeter** [ekosman/AnomalyDetectionCVPR2018-Pytorch#15]
Hi 
Agin thank you for all your work on this codebase @ekosman  :-)
Very small thing. It appears that the `FeaturesWriter` class in feature_extractor.py seem to have changed the format that is was saving in (from .txt to .pickle).
Alternatively, it is the read_features function that is using the "txt" format incorrectly.
Both formats work but just to clear up the code I would want to mention this change.

**Comment by ekosman** [comment]
@PHDPeter yea that seems to be a problem too. You midified lines 84 and 108 in `features_extractor.py` right? just asking so that I can fix that in this repo.

**Comment by PHDPeter** [comment]
I wanted to keep everything in plain text so I change the following
 _init_video(), line 89 to `self.path = path.join(dir, f"{video_name}.txt") #.pickle")`
 _is_new_video() line 113 to `new_path = path.join(dir, f"{video_name}.txt") #.pickle")`
read_features() line 134 to `file_path = f"{video_name}.txt"#.pickle"`
That way all are in plane texted I.e. t.t format.

**Comment by ekosman** [comment]
Ok, I've pushed a fix for this. Thanks!

**Comment by PHDPeter** [comment]
Awsome @ekosman glad I could help
