### ISSUE TITLE
Is it posble to use live video stream?

### ISSUE THREAD

**Issue by PHDPeter** [ekosman/AnomalyDetectionCVPR2018-Pytorch#16]
So I just want to make sure that we can use the trained model on a live (or close to live) video stream, such as from a web-cam or etc.
I know that in training the training/test data needs to be pre-processed by the C3D network before we can train the network with it. 
I know that C3D can be run in real-time (i.e. from webcam etc) so I just what to make sure that it would be possible to feed in live data and get results in real-time, kind of hoping to have this running all the time on a live stream of a cam for abnormal animal behaver etc.

Has anyone tried this and what kind of performance could you get form it if you did?

**Comment by ekosman** [comment]
I neither tried nor heard of works trying to use this in real time. However, I'd consider using predictions for each video clip, without using 32 segments with averaging. You can play with the clip stride, e.g. clip stride of 1 frame so you you make a prediction each frame, or clip stride of 10 to make a prediction every 10 frames.

**Comment by PHDPeter** [comment]
For anyone following these issues it was added to the code base now, so enjoy
