### ISSUE TITLE
TypeError: 'dict' object is not callable. 

### ISSUE THREAD

**Issue by asif-nuaa** [ekosman/AnomalyDetectionCVPR2018-Pytorch#171]
I am getting TypeError, when I try to execute the command. 

c:\> python video_demo.py --feature_extractor "features/c3d.pickle" --ad_model "pretrained/MFNet3D_UCF-101_Split-1_96.3.pth" --n_segments 32

would you please give more desciption about the parameters (feature_extractor, --ad_model, path-to-pretrained-fe) and their possible values.

**Comment by ekosman** [comment]
Thanks for reporting!

Could you please paste here the complete stack trace?

**Comment by ekosman** [comment]
You need to pass a valid AD model to to option `--ad_model`. You can find such models under `exps/`.

See the following command for example:
```python video_demo.py --feature_extractor pretrained/c3d.pickle --ad_model exps/c3d/models/epoch_80000.pt --n_segments 32```
