### ISSUE TITLE
Loading a checkpoint when running TrainingAnomalyDetector_public

### ISSUE THREAD

**Issue by SkyWalkerJJJ** [ekosman/AnomalyDetectionCVPR2018-Pytorch#173]
When I load an existed checkpoint [this line](https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/blob/69b932259eacccb79e5df99c002674b4e902e6a2/TrainingAnomalyDetector_public.py#L98), an error shows below.
My question is should the code define something as 
network = AnomalyDetector(args.feature_dim)
model = TorchModel.load_model(args.checkpoint)

Not really sure about the coding structure of TorchModel, so I want to confirm with you is it right to add network = AnomalyDetector(args.feature_dim) before it, and it will work perfectly?

```
Traceback (most recent call last):
  File "train_anomaly_detector.py", line 153, in <module>
    criterion = RegularizedLoss(network, custom_objective).to(device)
NameError: name 'network' is not defined
```

**Comment by ekosman** [comment]
Definitely! Thanks for reporting this. I will fix it soon.
