### ISSUE TITLE
regarding to Test_Annotation.txt. 

### ISSUE THREAD

**Issue by cervantes-loves-ai** [ekosman/AnomalyDetectionCVPR2018-Pytorch#18]
a bit confuse about test_annotation.txt formate. here is 2 examples from Test_Annotation.txt. if I am right than the first example have have 2 number 30 and 90 which represents frame number and -1 shows anomaly on those frames, but don't understand clearly example number 2. 

1.  RoadAccidents/RoadAccidents021_x264.mp4 155 RoadAccidents 30 90 -1 -1.  

2.  Testing_Normal_Videos_Anomaly/Normal_Videos_872_x264.mp4 530 Normal -1 -1 -1 -1

**Comment by cervantes-loves-ai** [comment]
hope will get from help from someone. thanks in advance..

**Comment by ekosman** [comment]
The numbers indicates the range of frames where anomalies occure. 
30 90 -1 -1 means anomaly between frames 30-90.
-1 -1 means no second anomaly in the video.

Notice that all normal video are annotated with -1 -1 -1 -1, thus no anomalies in these videos.
All anomaly videos have at least one pair (and at most two pairs) of numbers, indicating the frames range.
