### ISSUE TITLE
TrainingAnomalyDetector_public.py and generate_ROC.py  same error occurred

### ISSUE THREAD

**Issue by nbw999** [ekosman/AnomalyDetectionCVPR2018-Pytorch#212]
Hi, I have used C3D Precomputed Features  and  c3d model in the exps directory. I followed the command without modifying any other parts

Error：
return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype

**Comment by AbhinavJangra29** [comment]
hi here for seeking help! have you successfully infered the model even once? i am facing a lot of errors looking forward if you can help!

**Comment by ekosman** [comment]
Hi,

I just ran the script now, and experienced a different bug (wrong tensor dtypes apparently, not sure why that didn't happen before) and fixed it right away in #216 . Now it seems to work for me. Can you pull `main` again and try?

**Comment by ekosman** [comment]
Closing this as it seems to be fixed and no response from the author.
