### ISSUE TITLE
Mat1 and Mat2 shapes cannot be multiplied.

### ISSUE THREAD

**Issue by sania96** [ekosman/AnomalyDetectionCVPR2018-Pytorch#230]
Hi, Very Impressive work you have done, i wanted to mention that i am using pre computed resnet features and now trying to run the anomaly detection model training code but i am getting this error:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1920x2048 and 4096x512)

Can you please help me why am i getting this error?

Regards,

**Comment by ekosman** [comment]
Hi, can you give me the command you are trying to run?

**Comment by sania96** [comment]
Hey, Resolved The Error, Thanks..
