### ISSUE TITLE
Error on AD_live_perdiction expected np.ndarray (got NoneType)

### ISSUE THREAD

**Issue by yosagaf** [ekosman/AnomalyDetectionCVPR2018-Pytorch#26]
Hi can someone help how to resolve this error thanks. 

 File "AD_live_perdiction.py", line 364, in <module>
    testing()
  File "AD_live_perdiction.py.py", line 355, in testing
    sigle_y_pred = AD_sigle_perdiction(ad_model_dir, avg_segments, device=device,lengths=16,network=ad_net)
  File "demo_live.py", line 216, in AD_sigle_perdiction
    c3d_features=torAD_live_perdiction.pych.from_numpy(c3d_features)
TypeError: expected np.ndarray (got NoneType)

**Comment by PHDPeter** [comment]
Hi
looks like you are not providing the "c3d_features" variable? can you show us what you get for the `type(c3d_features)` or `len(c3d_features)`
Might help to get to bottom of it
