### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ChunmianLin** [ekosman/AnomalyDetectionCVPR2018-Pytorch#27]
Hello everyone, could you please provide the UCF dataset? I cannot pull it from the author's instruction due to some unknown error.

**Comment by NitinDatta8** [comment]
https://www.dropbox.com/sh/75v5ehq4cdg5g5g/AABvnJSwZI7zXb8_myBA0CLHa?dl=0

This is the second link and it seems to work

**Comment by ChunmianLin** [comment]
@NitinDatta8 Thanks. I have downloaded data from this link, but the data has been corrupted and I cannot open it.
could you please send me the data?

**Comment by NitinDatta8** [comment]
Could you please tell which file is corrupted.
At the moment I only have 2 zip files downloaded on my local..

**Comment by ChunmianLin** [comment]
@NitinDatta8 Thanks for reply. I cannot pull the data of **'Training_Normal_Part_1.zip'** and **'Training_Normal_Part_2.zip'**.
Many thanks for your help.

**Comment by ChunmianLin** [comment]
I think you can store them in google drive so that I could download.

**Comment by ekosman** [comment]
Hey,
This is the original link to the dataset posted by the paper's author. Are you sure it is downloaded properly?

**Comment by ChunmianLin** [comment]
@ekosman Thanks. I have failed to download data from this link several time, and the error message shows 'the file has been corrupted' when I want to open 'Training_Normal_Video_Part_1.zip' and 'Training_Normal_Video_Part_2.zip'.
Could you upload the data in google drive or baiduyun drive, so that I could try it again?

**Comment by Chuttyboy** [comment]
> https://www.dropbox.com/sh/75v5ehq4cdg5g5g/AABvnJSwZI7zXb8_myBA0CLHa?dl=0
> 
> This is the second link and it seems to work

@ekosman @NitinDatta8 

I got a 404 error when I use the given above link. kind request you to suggest any alternative dataset link 

Thanks
