### ISSUE TITLE
about AUC

### ISSUE THREAD

**Issue by henrryzh1** [ekosman/AnomalyDetectionCVPR2018-Pytorch#3]
hi,thanks for the torch code, it realy helped me. i run your code ,but the AUC score has always been 67%, i changed the parameters according the paper, nothing changed. i dont know whats the matter.

**Comment by ekosman** [comment]
@henrryzh1 I'm uploading the pre-computed features now, please try to use them when the upload is done

**Comment by henrryzh1** [comment]
> @henrryzh1 I'm uploading the pre-computed features now, please try to use them when the upload is done

Thanks，i cant wait to try

**Comment by ekosman** [comment]
Added link in README

**Comment by henrryzh1** [comment]
Thanks for the pre-computed features, i trained the code with those features,but i still got 0.71 AUC .i tested with https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/blob/master/exps/model_ep-20000.pth, i got 0.72. Then i used the the extraction model(c3d.pickle,ucf_caffee.pth) from https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/1,the AUC is still 0.67. it really bothers me.
