### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by ezzatmostafa96** [ekosman/AnomalyDetectionCVPR2018-Pytorch#32]
Is there any colab for all this?

**Comment by ekosman** [comment]
@ezzatmostafa96 
I'm planning creating a colab for video visualization which requires a pretrained model

**Comment by ezzatmostafa96** [comment]
when will you finish it?
Also, is there like a steps to go with in running the files. thanks

**Comment by ekosman** [comment]
The README.md closely describes the required steps. However, there are some bugs reported previously. Some of them are already solved in another branch but I won't merge until it works perfectly. After that, I intend to create the colab. The thing is that I don't have a free machine for this so I run it on my personal mac and it takes quite a while.

**Comment by ekosman** [comment]
There's a notebook directory for this.
