### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ezzatmostafa96** [ekosman/AnomalyDetectionCVPR2018-Pytorch#33]
feature_extractor.py: error: unrecognized arguments: --annotation_path Train_Annotation.txt --annotation_path_test Test_Annotation.txt

**Comment by ezzatmostafa96** [comment]
python feature_extractor.py --dataset_path "/content/AnomalyDetectionCVPR2018-Pytorch/Anomaly-Videos-Part-1/Abuse" --annotation_path "Train_Annotation.txt" --annotation_path_test "Test_Annotation.txt" --pretrained_3d "c3d.pickle"

I ranned it this way

**Comment by ekosman** [comment]
This is a well-known problem that is going to be fixed in V2.

**Comment by ekosman** [comment]
Merged a branch that fixes this
