### ISSUE TITLE
Pre-computed features

### ISSUE THREAD

**Issue by WuJie1010** [ekosman/AnomalyDetectionCVPR2018-Pytorch#4]
Firstly, First of all, thank you for sharing the code~
I find that I use "feature_extratcor.py" to extract the c3d feature can not obtain the same performance as your “pre-computed feature”.(about 5% performance drop~) I want to figure out how you get the pre-computed feature (from your shared link~). Thanks~

**Comment by henrryzh1** [comment]
Thanks for the shared features, but i find it maybe loss 90 features. then i extract the c3d feature, i met same problem.

**Comment by hthoai** [comment]
Hi @ekosman ,
Could you please upload all pre-computed features?! I found that your link didn't contain full of the features for 1900 videos ;-;

**Comment by ekosman** [comment]
Hi @hthoai 
I'll definitely check what messed this up when I'll have time for this. That's why this issue is still open.

**Comment by yosagaf** [comment]
Hi, any solution ?

**Comment by ekosman** [comment]
@yosagaf 

I'm very busy in the near future so I won't be able to work on that. Sorry :(

**Comment by PHDPeter** [comment]
@WuJie1010 is the issues that not all the videos in the list end up with there own pre-computed feature?
If so I think we have fixed this via a different issue (https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/20)

On upload all pre-computed features, I have ones I have done myself. However, the files are very big and took me a long while to get them all run on AWS so not sure I can just post them anywhere, sorry.

**Comment by fatandmarsiano** [comment]
@PHDPeter does your resulted computed features using this repository relatively  the same compared to the one extracted from the original caffe implementation?

for the Abuse_001 videos I got (first few lines)
`9.910389053402469e-06 0.0 0.05880896374583244 0.0 0.029203234240412712 0.018749289214611053 0.028914393857121468 0.0 0.0 0.0033053637016564608 0.0 0.012286401353776455 0.008645551279187202 0.02548288367688656 0.0 0.0 0.0 0.0`

compared to the caffe
`0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.001164 0.000000 0.006690 0.000000 0.000000 0.000000 0.002213 0.`

which is quite different

**Comment by PHDPeter** [comment]
So what you have there for Abuse_001 video looks about right to what I have but I would say that the features stored in the txt files are not meant to be the output from the C3D network, i.e. what you would get if you just run the C3D network on the video.
Either way, if you are looking into the difference between the C3D method used here and that done with Caffe, I would suggest talking to people that made this imputation of the C3D for pytorch ([](https://github.com/DavideA/c3d-pytorc)h)

**Comment by ekosman** [comment]
Also, these pre-computed features are normalized and sliced into 32 chunks as described in the paper.

**Comment by ekosman** [comment]
Uploaded new pre-computed features for all videos.
