### ISSUE TITLE
video_demo  problems

### ISSUE THREAD

**Issue by ekosman** [ekosman/AnomalyDetectionCVPR2018-Pytorch#48]
@ekosman 
Hi
I'm trying to upload the new weights, and I'm getting this.
![Screenshot from 2020-12-04 16-25-44](https://user-images.githubusercontent.com/54175926/101181844-a5faf080-364d-11eb-8433-e441fb94693d.png)
Any idea why I'm getting this ?

Also, I guess there might be some issues with code versions.
in **video_demo.py** you have:
`from data_loader import VideoIterTrain`

but in **data_loader.py**, there is only:
`class VideoIter(data.Dataset):`

So, it's not possible just to run the  **video_demo.py**.

I tried to rename VideoIterTrain to VideoIter, but I'm getting errors with the arguments.
So, I scanned the reposetory history and found some old **data_loader.py** files and there was VideoIterTrain. Eventually after some fixes, I was able to run **video_demo.py**.

But now, I have problems with uploading new models.

Thanks.

_Originally posted by @volodymyrkepsha in https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/39#issuecomment-738863712_

**Comment by ekosman** [comment]
Hi @volodymyrkepsha

I'll reference this here. I've made a few updates to the data loaders and probably broke the demo script. I will solve this as soon as I have time for it.

**Comment by volodymyrkepsha** [comment]
@ekosman hi

More info on models:
![Screenshot from 2020-12-04 17-15-10](https://user-images.githubusercontent.com/54175926/101187152-46ecaa00-3654-11eb-8d98-fb27753e69ed.png)

As I noticed the only model that works is model_ep-20000.pth (which is 24Mb) and all other fails. It looks like they were saved not properly, I guess. 

Thanks !

**Comment by ekosman** [comment]
@volodymyrkepsha They work for me. What error do you get?

**Comment by volodymyrkepsha** [comment]
@ekosman 
```
raceback (most recent call last):
  File "video_demo.py", line 288, in <module>
    y_pred=AD_perdiction(model_dir, dir_list, device=device)
  File "video_demo.py", line 122, in AD_perdiction
    net.load_checkpoint(pretrain_path=model_path, epoch=20000)
  File "/home/volodymyr/SITA_3/AnomalyDetectionCVPR2018-Pytorch/network/model.py", line 64, in load_checkpoint
    checkpoint = torch.load(pretrain_path, map_location='cpu')
  File "/home/volodymyr/SITA_3/c3d-pytorch/venv/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/volodymyr/SITA_3/c3d-pytorch/venv/lib/python3.6/site-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: **A load persistent id instruction was encountered,
but no persistent_load function was specified.**

```
Obviously the issue is with the serialization, it can't read the model correctly.
Isn't it strange that the only model which works on my side is the 24Mb one?

When you have free time, just try to pull the repository and try to run it with the new models.

Anyway thanks for your time and cooperation.

**Comment by ekosman** [comment]
Yeah, it seems like the code for video_demo is broken; for now, I'll mention this in the README and solve it when I can. thanks for reporting.

**Comment by mrkstt** [comment]
Hi @ekosman ,
Thanks for this outstanding repo. I have tested feature extractor, Training model (50k epoch), and generate ROC, all works perfectly. I obtained 0.70 of ROC area.
Unfortunately, the video demo didn't work. I then used previous repo from @PHDPeter (https://github.com/PHDPeter/AnomalyDetectionCVPR2018-Pytorch), and finally able to show the result (plot is very slow). Then to speed up, I modified the code and using original GUI demo from Waqqas (CVPR'18) Unluckily, the plot might not work perfectly (incorrect prediction). If the video demo can be corrected, that would be great. My modified code and result are as follow:

`from network.c3d import C3D #network.
from data_loader import VideoIterTrain
import torch

from utils.utils import set_logger, build_transforms

import os

from feature_extractor import FeaturesWriter
from tqdm import tqdm


from network.anomaly_detector_model import AnomalyDetector, RegularizedLoss, custom_objective
from network.model import static_model

from features_loader import FeaturesLoaderVal


import numpy as np
import numpy.matlib

import cv2
import matplotlib.pyplot as plt
import matplotlib.animation as animation

import argparse
import time
from math import factorial
import pytorch_wrapper as pw

parser = argparse.ArgumentParser(description="Video demo maker")

parser.add_argument('--video_parth_list', default=["/home/tekom/nf/AnomalyDetectionCVPR2018-Pytorch/videos/Abuse004_x264.mp4"],
                    help="list of videos to be used for demo")
parser.add_argument('--features_dir', default="/home/tekom/nf/AnomalyDetectionCVPR2018-Pytorch/features/",
                    help="path to dir where you want the featuers saved")
parser.add_argument('--model_dir', default='/home/tekom/nf/AnomalyDetectionCVPR2018-Pytorch/exps/model_final',
                    help="path to the tarined AD model")


args = parser.parse_args()

video_parth_list = args.video_parth_list
features_dir = args.features_dir
model_dir = args.model_dir

def figure2opencv(figure):
    figure.canvas.draw()
    img = np.fromstring(figure.canvas.tostring_rgb(), dtype=np.uint8, sep='')
    img = img.reshape(figure.canvas.get_width_height()[::-1] + (3,))
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    return img

def cd3_extartion(video_parth,device=None):

    batch_size=1
    train_frame_interval=int(2)
    clip_length=int(16)


    single_load=True #should not matter
    home=os.getcwd()
    pretrained_3d=home+"/exps/c3d.pickle"

    if device==None:
        device = torch.device("cuda" if torch.cuda.is_available()
                          else "cpu")


    #Load clips
    print("doing train loader")
    train_loader = VideoIterTrain(dataset_path=None,
                                  annotation_path=video_parth,
                                  clip_length=clip_length,
                                  frame_stride=train_frame_interval,
                                  video_transform=build_transforms(),
                                  name='train',
                                  return_item_subpath=False,
                                  single_load=single_load)
    print("train loader done, train_iter now")
    train_iter = torch.utils.data.DataLoader(train_loader,
                                             batch_size=batch_size,
                                             shuffle=False,
                                             num_workers=32,  # 4, # change this part accordingly
                                             pin_memory=True)

    #Possesing with CD3
    print("Now loading the data to C3D netowr")
    network = C3D(pretrained=pretrained_3d)
    network.to(device)

    if not os.path.exists(features_dir):
        os.mkdir(features_dir)

    features_writer = FeaturesWriter()

    dir_list=[]

    for i_batch, (data, target, sampled_idx, dirs, vid_names) in tqdm(enumerate(train_iter)):
        with torch.no_grad():
            outputs = network(data.cuda())

            for i, (dir, vid_name, start_frame) in enumerate(zip(dirs, vid_names, sampled_idx.cpu().numpy())):
                dir_list.append([dir,vid_name])
                dir = os.path.join(features_dir, dir)
                features_writer.write(feature=outputs[i], video_name=vid_name, start_frame=start_frame, dir=dir)

    features_writer.dump()
    return dir_list

def AD_perdiction(model_dir,dir_list,device=None):

    if device==None:
        device = torch.device("cuda" if torch.cuda.is_available()
                          else "cpu")

    #pediction of AD with pertrain network
    network = AnomalyDetector()
    network.to(device)
    net = static_model(net=network,
                           criterion=RegularizedLoss(network, custom_objective).cuda(),
                           model_prefix=model_dir,
                           )
    
    model_path = net.get_checkpoint_path(50000) #(20000)
    net.load_checkpoint(pretrain_path=model_path, epoch=50000) #20000)
    
    net.net.to(device)
    
    from annotation_methods import annotatate_file
    annotation_path=annotatate_file(video_parth,dir_list,normal=True,file_name="Demo_anmotation")

    #runing vedio in to network
    data_loader = FeaturesLoaderVal(features_path=features_dir,
                                    annotation_path=annotation_path)

    data_iter = torch.utils.data.DataLoader(data_loader,
                                            batch_size=1,
                                            shuffle=False,
                                            num_workers=1,  # 4, # change this part accordingly
                                            pin_memory=True)
    print("it is over")

    for features, start_end_couples, feature_subpaths, lengths in tqdm(data_iter):
        # features is a batch where each item is a tensor of 32 4096D features
        features = features.to(device)
        with torch.no_grad():
            input_var = torch.autograd.Variable(features)
            outputs = net.predict(input_var)[0]  # (batch_size, 32)
            outputs = outputs.reshape(outputs.shape[0], 32)
            for vid_len, couples, output in zip(lengths, start_end_couples, outputs.cpu().numpy()):
                y_true = np.zeros(vid_len)
                segments_len = vid_len // 32
                for couple in couples:
                    if couple[0] != -1:
                        y_true[couple[0]: couple[1]] = 1
                y_pred = np.zeros(vid_len)
                print()
                for i in range(32):
                    segment_start_frame = i * segments_len
                    segment_end_frame = (i + 1) * segments_len
                    y_pred[segment_start_frame: segment_end_frame] = output[i]

    print(y_true)
    print(y_pred)
    print("it is over")
    return y_pred

def savitzky_golay(y, window_size, order, deriv=0, rate=1):
    #try:
    window_size = np.abs(np.int(window_size))
    order = np.abs(np.int(order))
    #except ValueError, msg:
    #    raise ValueError("window_size and order have to be of type int")

    if window_size % 2 != 1 or window_size < 1:
        raise TypeError("window_size size must be a positive odd number")

    if window_size < order + 2:
        raise TypeError("window_size is too small for the polynomials order")

    order_range = range(order + 1)

    half_window = (window_size - 1) // 2
    b = np.mat([[k ** i for i in order_range] for k in range(-half_window, half_window + 1)])
    m = np.linalg.pinv(b).A[deriv] * rate ** deriv * factorial(deriv)
    firstvals = y[0] - np.abs(y[1:half_window + 1][::-1] - y[0])
    lastvals = y[-1] + np.abs(y[-half_window - 1:-1][::-1] - y[-1])
    y = np.concatenate((firstvals, y, lastvals))
    return np.convolve(m[::-1], y,mode='valid')


def GUI(video_parth,y_pred,save="Just save",s_path="output_video"):
    print(video_parth)
    cap = cv2.VideoCapture(video_parth)
    #Total_frames = cap.get(cv2.CV_CAP_PROP_FRAME_COUNT)
    print(cv2)
    Total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    total_segments = np.linspace(1, Total_frames, num=33)
    total_segments = total_segments.round()
    
    Frames_Score = []
    count = -1;
    for iv in range(0, 32):
        F_Score = np.matlib.repmat(y_pred[iv],1,(int(total_segments[iv+1])-int(total_segments[iv])))
        count = count + 1
        if count == 0:
            Frames_Score = F_Score
        if count > 0:
            Frames_Score = np.hstack((Frames_Score, F_Score))

    cap = cv2.VideoCapture((video_parth))
    while not cap.isOpened():
        cap = cv2.VideoCapture((video_parth))
        cv2.waitKey(1000)
        print ("Wait for the header")

    pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
    Total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)

    print ("Anomaly Prediction")
    x = np.linspace(1, Total_frames, Total_frames)
    scores = Frames_Score
    scores1=scores.reshape((scores.shape[1],))
    scores1 = savitzky_golay(scores1, 101, 3)
    plt.close()
    break_pt=min(scores1.shape[0], x.shape[0])
    plt.axis([0, Total_frames, 0, 1])
    i=0;
    while True:
        flag, frame = cap.read()
        if flag:
            i = i + 1
            cv2.imshow('video', frame)
            jj=i%25
            if jj==1:
                plt.plot(x[:i], y_pred[:i], color='r', linewidth=3)
                plt.draw()
                plt.pause(0.000000000000000000000001)

            pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
            #print (str(pos_frame) + " frames")
        else:
            # The next frame is not ready, so we try to read it again
            cap.set(cv2.CAP_PROP_POS_FRAMES, pos_frame - 1)
            print("frame is not ready")
            # It is better to wait for a while for the next frame to be ready
            cv2.waitKey(1000)

        if cv2.waitKey(10) == 27:
                break
        if cap.get(cv2.CAP_PROP_POS_FRAMES)== break_pt:
            #cap.get(cv2.CAP_PROP_FRAME_COUNT):
            # If the number of captured frames is equal to the total number of frames,
            # we stop
            break

    # DISPLAY_IMAGE_SIZE = 500
    # BORDER_SIZE = 50#100
    # FIGHT_BORDER_COLOR = (0, 0, 255)
    # NO_FIGHT_BORDER_COLOR = (0, 255, 0)

    # plot_range = 100
    # # violenceDetector = ViolenceDetector()
    # videoReader = cv2.VideoCapture(video_parth)
    # isCurrentFrameValid, currentImage = videoReader.read()

    # if save == True or save == "Just save":
    #     #fps = videoReader.get(cv2.CV_CAP_PROP_FPS)
    #     fps = videoReader.get(cv2.CAP_PROP_FPS)
    #     fourcc = cv2.VideoWriter_fourcc(*'XVID')
    #     out = cv2.VideoWriter(s_path+'.avi', fourcc,fps,(600, 300))

    # #farme_window=[0]*clip_length
    # fig = plt.figure()
    # farme_cout = 0
    # length = int(videoReader.get(cv2.CAP_PROP_FRAME_COUNT))
    # while isCurrentFrameValid:
    #     farme_cout = farme_cout + 1

    #     targetSize = DISPLAY_IMAGE_SIZE - 2 * BORDER_SIZE
    #     currentImage = cv2.resize(currentImage, (targetSize, targetSize))

    #     NO_FIGHT_BORDER_COLOR = NO_FIGHT_BORDER_COLOR
    #     resultImage = cv2.copyMakeBorder(currentImage,
    #                                      BORDER_SIZE,
    #                                      BORDER_SIZE,
    #                                      BORDER_SIZE,
    #                                      BORDER_SIZE,
    #                                      cv2.BORDER_CONSTANT,
    #                                      value=NO_FIGHT_BORDER_COLOR)

    #     resultImage = cv2.resize(resultImage, (300, 300))

    #     #fig = plt.figure()
    #     # print(pec_store)
    #     #print(farme_cout)
    #     #print(y_pred[farme_cout-1])
    #     plt.plot(farme_cout, y_pred[farme_cout-1], color='green', marker='o', linestyle='-', linewidth=2, markersize=2)
    #     # plt.plot(it_uesed, pec_store2, c="r")
    #     # plt.xlim()
    #     plt.ylim(0, 1.0)
    #     if farme_cout<100:
    #         plt.xlim(0, 100)
    #     else:
    #         plt.xlim(farme_cout-100, farme_cout+100)

    #     plt.xlim(0, length)
    #     plot_img = figure2opencv(fig)
    #     plot_img = cv2.resize(plot_img, (300, 300))  # (0, 0), None, .25, .25)

    #     resultImage = np.concatenate((resultImage, plot_img), axis=1)


    #     if save == True or save=="Just save":
    #         # Write the frame into the file 'output.avi'
    #         print("saving")
    #         out.write(resultImage)

    #     if save!="Just save":
    #         cv2.imshow("Violence Detection", resultImage)
    #     else:
    #         print(str(farme_cout)+"/"+str(length))

    #     userResponse = cv2.waitKey(1)
    #     if userResponse == ord('q'):
    #         videoReader.release()
    #         cv2.destroyAllWindows()
    #         break

    #     else:
    #         isCurrentFrameValid, currentImage = videoReader.read()


    # if save == True or save == "Just save":
    #     videoReader.release()
    #     out.release()

    # cv2.destroyAllWindows()

    # #results and video play at the same time

if __name__ == '__main__':
    home=os.getcwd()

    args = parser.parse_args()

    video_parth_list=args.video_parth_list
    features_dir=args.features_dir
    model_dir=args.model_dir

    # # make video file format
    # if "peter" in home:
    #     video_parth = "/media/peter/Maxtor/UCF_Crimes/Videos/Fighting/Fighting047_x264.mp4"
    # else:
    #     video_parth = "/home/barbara/Desktop/Fighting047_x264.mp4"


    # from os import listdir
    # from os.path import isfile, join
    # mypath="/media/peter/Maxtor/UCF_Crimes/Videos/Fighting"
    # #video_parth_list = [mypath+"/"+f for f in listdir(mypath) if isfile(join(mypath, f))]
    # #print("lenght "+str(len(video_parth_list)))
    #video_parth_list=["/media/peter/Maxtor/UCF_Crimes/Videos/Fighting/Fighting039_x264.mp4"]

    #features_dir = r"./demo_video"

    # defining pertrained modle of AD
    #model_dir = r'/home/peter/Documents/actionID/AnomalyDetectionCVPR2018-Pytorch-master/short_60_low_mem/exps/model'
    # "/home/peter/Documents/actionID/AnomalyDetectionCVPR2018-Pytorch-master/AnomalyDetectionCVPR2018-Pytorch-master/short_60_low_mem/exps/model"

    device = torch.device("cuda" if torch.cuda.is_available()
                          else "cpu")

    for video_parth in video_parth_list:
        dir_list=cd3_extartion(video_parth,device=device)
        y_pred=AD_perdiction(model_dir, dir_list, device=device)

        import pickle
        print(features_dir[1:]+dir_list[0][0]+"/"+dir_list[0][1]+'_y_pred.pkl')
        with open("/"+features_dir[1:]+dir_list[0][0]+"/"+dir_list[0][1]+'_y_pred.pkl', 'wb') as f:
            pickle.dump(y_pred, f)
        #with open(features_dir+dir_list[0][0]+"/"+dir_list[0][1]+'_y_pred.pkl', 'rb') as f:
        #    y_pred = pickle.load(f)
        print('=====================DONE PREDICTION=======================')
        GUI(video_parth, y_pred,save="00 Just save",s_path=features_dir+dir_list[0][0]+"/"+dir_list[0][1]+"_demoe")`


![Screenshot from 2020-12-18 23-20-30](https://user-images.githubusercontent.com/19767644/102636829-b5b72080-4187-11eb-814a-2878ff840162.png)

**Comment by ekosman** [comment]
Hi @mrkstt I just created a new GUI now. Can you check it if it suits your needs?

**Comment by mrkstt** [comment]
Hi @ekosman ,

The codes work properly, but the final prediction seems still has an error, as follow:

defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
/home/tekom/nf/NEW_Pytorch_AD/AnomalyDetectionCVPR2018-Pytorch/videos/RoadAccidents002_x264.mp4
1049it [02:16,  7.67it/s]
Traceback (most recent call last):
  File "video_demo.py", line 252, in open_file
    self.y_pred = y_pred.numpy().flatten()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Aborted (core dumped)

**Comment by ekosman** [comment]
@mrkstt Just patched this.

**Comment by mrkstt** [comment]
Hi @ekosman , thanks for your prompt patch.
Unfortunately, I'm working on Ubuntu and the QT seems not work properly. Then, I modified your recent code by separating the video show and corresponding plot. It works, but unluckily the prediction is not as accurate as original work from Waqqas. Here is my newest code using your recent patch:

```
from data_loader import SingleVideoIter
from feature_extractor import to_segments
from network.anomaly_detector_model import AnomalyDetector
from network.c3d import C3D
from utils.utils import build_transforms
from os import path
import pytorch_wrapper as pw

import torch
import logging
import os

from feature_extractor import FeaturesWriter
from tqdm import tqdm

from features_loader import FeaturesLoaderVal


import numpy as np
import numpy.matlib
from math import factorial

import cv2
import matplotlib.pyplot as plt
from scipy.ndimage.filters import gaussian_filter1d

import argparse
parser = argparse.ArgumentParser(description="Video Demo For Anomaly Detection")

parser.add_argument('--feature_extractor',
                    required=False,
                    default='/home/tekom/nf/NEW_Pytorch_AD/AnomalyDetectionCVPR2018-Pytorch/exps/models/c3d.pickle',
                    help='path to the 3d model for feature extraction')
parser.add_argument('--feature_method',
                    default='c3d',
                    choices=['c3d', 'mfnet'],
                    help='method to use for feature extraction')
parser.add_argument('--ad_model',
                    required=False,
                    default='/home/tekom/nf/NEW_Pytorch_AD/AnomalyDetectionCVPR2018-Pytorch/exps/models/model_final_50000.weights',
                    help="path to the trained AD model")
parser.add_argument('--n_segments',
                    type=int,
                    default=32,
                    help='number of segments to use for features averaging')

args = parser.parse_args()

#video_parth_list = args.video_parth_list
#features_dir = args.features_dir
#model_dir = args.model_dir

feature_extractor = args.feature_extractor
feature_method = args.feature_method
ad_model = args.ad_model
n_segments = args.n_segments

def load_models(feature_extractor_path, ad_model_path, features_method='c3d', device='cuda'):
    """
    Loads both feature extractor and anomaly detector from the given paths
    :param feature_extractor_path: path of the features extractor weights to load
    :param ad_model_path: path of the anomaly detector weights to load
    :param features_method: name of the model to use for features extraction
    :param device: device to use for the models
    :return: anomaly_detector, feature_extractor
    """
    print(feature_extractor_path)
    assert path.exists(feature_extractor_path)
    assert path.exists(ad_model_path)

    feature_extractor, anomaly_detector = None, None

    if features_method == 'c3d':
        logging.info(f"Loading feature extractor from {feature_extractor_path}")
        feature_extractor = C3D(pretrained=feature_extractor_path)
    else:
        raise NotImplementedError(f"Features extraction method {features_method} not implemented")

    logging.info(f"Loading anomaly detector from {ad_model_path}")
    feature_extractor = feature_extractor.to(device).eval()
    anomaly_detector = pw.System(model=AnomalyDetector(), device=device)
    anomaly_detector.load_model_state(ad_model_path)
    anomaly_detector = anomaly_detector.model.eval()

    return anomaly_detector, feature_extractor

def figure2opencv(figure):
    figure.canvas.draw()
    img = np.fromstring(figure.canvas.tostring_rgb(), dtype=np.uint8, sep='')
    img = img.reshape(figure.canvas.get_width_height()[::-1] + (3,))
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    return img


def features_extraction(video_path, model, device, batch_size=8, frame_stride=1, clip_length=16, n_segments=32, bar=None):
    """
    Extracts features of the video. The returned features will be returned after averaging over the required number of
    video segments.
    :param video_path: path of the video to predict
    :param model: model to use for feature extraction
    :param device: device to use for loading data
    :param batch_size: batch size to use for loading data
    :param frame_stride: interval between frames to load
    :param clip_length: number of frames to use for loading each video sample
    :param n_segments: how many chunks the video should be divided into
    :return: features list (n_segments, feature_dim), usually (32, 4096) as in the original paper
    """
    device = torch.device("cuda" if torch.cuda.is_available()
                          else "cpu")
    data_loader = SingleVideoIter(clip_length=clip_length,
                                  frame_stride=frame_stride,
                                  video_path=video_path,
                                  video_transform=build_transforms(mode=args.feature_method),
                                  return_label=False)
    data_iter = torch.utils.data.DataLoader(data_loader,
                                            batch_size=batch_size,
                                            shuffle=False,
                                            num_workers=4,  # 0, # change this part accordingly
                                            pin_memory=True)

    logging.info("Extracting features...")
    print(model)
    features = torch.tensor([])
    #network = C3D(pretrained=model)
    #network.to(device)
    network = C3D(pretrained=model)
    if device.type != 'cpu':
        network = torch.nn.DataParallel(network)
    network = network.to(device)

    with torch.no_grad():
        for i, data in tqdm(enumerate(data_iter)):
            #outputs = model(data.to(device)).detach().cpu() #remark by Kahlil, please check!
            outputs = network(data.to(device)).detach().cpu()
            features = torch.cat([features, outputs])

    features = features.numpy()
    print(features)
    return to_segments(features, n_segments)

def ad_prediction(model, features, device='cuda'):
    """
    Creates frediction for the given feature vectors
    :param model: model to use for anomaly detection
    :param features: features of the video clips
    :param device: device to use for loading the features
    :return: anomaly predictions for the video segments
    """
    logging.info(f"Performing anomaly detection...")
    features = torch.tensor(features).to(device)
    with torch.no_grad():
        preds = model(features)

    #return preds.detach().cpu().numpy().flatten()
    return preds.detach().cpu().numpy()
    
def GUI(video_path,y_pred,save,s_path="output_video"):
    print(video_path)
    cap = cv2.VideoCapture(video_path)
    #Total_frames = cap.get(cv2.CV_CAP_PROP_FRAME_COUNT)
    print(cv2)
    Total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    #total_segments = np.linspace(1, Total_frames, num=33)
    #total_segments = total_segments.round()
    
    cap = cv2.VideoCapture((video_path))
    while not cap.isOpened():
        cap = cv2.VideoCapture((video_path))
        cv2.waitKey(1000)
        print ("Wait for the header")

    pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
    Total_frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)

    print ("Anomaly Prediction")
    plt.close()
    plt.xlim(0, Total_frames)
    plt.ylim(-0.1, 1.1)
    incremental_index=0;
    i=0;
    no_fr_per_segm = Total_frames/32
    while True:
        flag, frame = cap.read()
        if flag:
            if i>no_fr_per_segm:
                incremental_index = incremental_index + 1
                i = 0
                
            cv2.imshow('video', frame)
            
            jj=pos_frame%25
            if jj==1:
                #print(pos_frame/1000)
                #print(y_pred[incremental_index])
                #ysmoothed = gaussian_filter1d(y_pred[incremental_index], sigma=2)
                plt.plot(pos_frame, y_pred[incremental_index], '*-')
                #plt.plot(x[:i], y_pred[:i], color='r', linewidth=3)
                plt.draw()
                plt.pause(0.000000000000000000000001)

            pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
            #print (str(pos_frame) + " frames")
            i = i + 1
        else:
            # The next frame is not ready, so we try to read it again
            cap.set(cv2.CAP_PROP_POS_FRAMES, pos_frame - 1)
            #print("frame is not ready")
            # It is better to wait for a while for the next frame to be ready
            cv2.waitKey(1000)

        if cv2.waitKey(10) == 27:
                break        

if __name__ == '__main__':
    home=os.getcwd()

    args = parser.parse_args()

    #video_parth_list=args.video_parth_list
    #features_dir=args.features_dir
    #model_dir=args.model_dir

    video_path='/home/tekom/nf/NEW_Pytorch_AD/AnomalyDetectionCVPR2018-Pytorch/videos/Explosion008_x264.mp4'

    anomaly_detector, feature_extractor = load_models(args.feature_extractor,
                                                      args.ad_model,
                                                      features_method=args.feature_method,
                                                      device=torch.device("cuda" if torch.cuda.is_available() else "cpu"), )

    device = torch.device("cuda" if torch.cuda.is_available()
                          else "cpu")

    print(args.n_segments)
    #for video_parth in video_parth_list:
    features = features_extraction(video_path,
                                        model=args.feature_extractor,
                                        device=device,
                                        n_segments=args.n_segments)

    y_pred = ad_prediction(model=anomaly_detector,
                            features=features,
                            device=device,) #AD_prediction

    GUI(video_path, y_pred,save="00ust save",s_path="test")
```
![Screenshot from 2020-12-21 11-49-04](https://user-images.githubusercontent.com/19767644/102740862-5c1b4580-4383-11eb-954f-5fb18146fd6f.png)
![Screenshot from 2020-12-21 11-50-42](https://user-images.githubusercontent.com/19767644/102740865-5e7d9f80-4383-11eb-9f5b-a7db7d743d81.png)

**Comment by ekosman** [comment]
@mrkstt  I suspect that it has something to do with the c3d features, as the AUC score doesn't perfectly match the paper's results.
I'm currently working on extracting features using another model, but I run it on my mac so it takes quite a while.
