### ISSUE TITLE
Pytorch version in environment.yml

### ISSUE THREAD

**Issue by maloq** [ekosman/AnomalyDetectionCVPR2018-Pytorch#51]
Version 1.2.0 of torch, stated in environment.yml seems to be outdated for this repo. While using generate_ROC.py with most recent models I've got an error:  " model_final_100000.weights zip archive (did you mean to use torch.jit.load()? ", and it has gone after upgrading PyTorch to 1.7.0 version. But maybe I'm wrong, so I raised this issue to clarify this

**Comment by ekosman** [comment]
This might be true. I presumably updated my torch while working on the repo lately and forgot to update this.
I'll update it when I have more time.

Thanks for reporting this.
