### ISSUE TITLE
getting VideoIter:: ERROR!! 

### ISSUE THREAD

**Issue by RachanaAgarwal** [ekosman/AnomalyDetectionCVPR2018-Pytorch#59]
Getting below error when running feature_extractor notebook.Same Getting same error when executing feature_extractor.py in windows environment

2020-12-24 06:41:50,683 VideoIter:: ERROR!! (Force using another index:
154)
torch.Size([0, 1, 1, 3]) x 162020-12-24 06:41:50,683 VideoIter:: ERROR!! (Force using another index:
154)
torch.Size([0, 1, 1, 3]) x 16
2020-12-24 06:41:50,688 VideoIter:: ERROR!! (Force using another index:
154)
torch.Size([0, 1, 1, 3]) x 162020-12-24 06:41:50,697 VideoIter:: ERROR!! (Force using another index:
154)
torch.Size([0, 1, 1, 3]) x 162020-12-24 06:41:50,700 VideoIter:: ERROR!! (Force using another index:
154)
torch.Size([0, 1, 1, 3]) x 16

**Comment by ekosman** [comment]
@RachanaAgarwal 
Can you provide more information, like what is the command you run?

**Comment by RachanaAgarwal** [comment]
Exact error with feature_extractor.py(on windows env) given below(above error is with feature_extractor notebook when running on collab)

command :python feature_extractor.py --dataset_path dataset --pretrained_3d exps/models/c3d.pickle --model_type c3d

--dataset_path dataset is => path to test video( just have single video Robbery_test_056_x264.mp4 ) for feature extraction
--num_workers ==> 4 as I was getting a paging error

python feature_extractor.py --dataset_path dataset --pretrained_3d exps/models/c3d.pickle --model_type c3d
2020-12-24 15:10:35,522 Loading feature extractor from exps/models/c3d.pickle
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
WARNING:root:VideoIter:: ERROR!! (Force using another index:
69)
not enough values to unpack (expected 2, got 1)
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
WARNING:root:VideoIter:: ERROR!! (Force using another index:
4)
not enough values to unpack (expected 2, got 1)
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
WARNING:root:VideoIter:: ERROR!! (Force using another index:
167)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
132)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
9)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
26)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
136)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
29)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
114)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
36)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
147)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
164)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
29)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
76)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
42)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
94)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
37)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
18)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
86)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
101)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
86)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
132)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
171)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
14)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
136)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
101)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
54)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
139)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
166)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
154)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
126)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
158)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
20)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
66)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
28)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
34)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
170)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
2)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
137)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
153)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
46)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
82)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
65)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
115)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
53)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
131)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
164)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
143)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
29)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
132)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
5)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
3)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
131)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
101)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
142)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
142)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
155)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
168)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
151)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
92)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
22)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
112)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
5)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
132)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
52)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
62)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
126)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
94)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
72)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
140)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
137)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
95)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
40)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
77)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
63)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
80)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
130)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
120)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
22)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
138)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
132)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
94)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
111)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
29)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
58)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
2)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
135)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
69)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
104)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
43)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
156)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
155)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
95)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
23)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
44)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
163)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
9)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:

**Comment by ekosman** [comment]
The script expects the data to be the same as the dataset, i.e. a directory containing some hierarchy. Please try passing a path to a directory for --dataset_path

**Comment by RachanaAgarwal** [comment]
yes, it's the path to the directory. Please let me know what exactly need to be done

Directory of  \AnomalyDetectionCVPR2018-Pytorch-master\dataset
which has this file
26-03-2020  08:23        18,125,482 Robbery_test_056_x264.mp4.mp4

**Comment by ekosman** [comment]
@RachanaAgarwal 
I created a new branch called `debug_video_loader`. This adds the line number of the exception in the warning message. Can you checkout this branch, run the code, and tell me the warning then?

**Comment by RachanaAgarwal** [comment]
@ekosman  Please find new logs

python feature_extractor.py --dataset_path dataset --pretrained_3d exps/models/c3d.pickle --model_type c3d

2020-12-25 10:36:52,041 Loading feature extractor from exps/models/c3d.pickle
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
WARNING:root:VideoIter:: ERROR!! (Force using another index:
36)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
36)
not enough values to unpack (expected 2, got 1)
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
WARNING:root:VideoIter:: ERROR!! (Force using another index:
21)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
21)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
128)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
128)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
149)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
149)
not enough values to unpack (expected 2, got 1)
C:\Users\racha\.conda\envs\adCVPR18\lib\site-packages\torchvision\io\video.py:116: UserWarning: The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. Please use pts_unit 'sec'.
  "The pts_unit 'pts' gives wrong results and will be removed in a "
WARNING:root:VideoIter:: ERROR!! (Force using another index:
91)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
91)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
61)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
61)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
100)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
100)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
25)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
25)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
84)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
84)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
17)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
17)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
2)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
2)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
40)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
40)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
40)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
40)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
129)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
129)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
118)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
118)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
157)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
157)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
10)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
10)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
121)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
121)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
11)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
11)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
164)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
164)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
143)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
143)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
53)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
53)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
51)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
51)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
74)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
74)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
159)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
159)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
11)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
11)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
80)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
80)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
63)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
63)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
138)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
138)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
165)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
165)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
64)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
64)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
85)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
85)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
149)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
149)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
135)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
135)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
120)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
120)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
110)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
110)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
56)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
56)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
54)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
54)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
33)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
33)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
153)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
153)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
20)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
20)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR!! (Force using another index:
89)
not enough values to unpack (expected 2, got 1)
WARNING:root:VideoIter:: ERROR (line number 71 !! (Force using another index:
89)
.
.
.
.
.

**Comment by ekosman** [comment]
@RachanaAgarwal 
I'm unable to recreate this bug.
I created a new directory containing one file: 
`F:\anomaly_data\videos\test\Arrest006_x264.mp4.mp4`

I run this command without any error:
`python feature_extractor.py --dataset_path "F:\anomaly_data\videos\test" --pretrained_3d C:\Users\eitan\PycharmProjects\AnomalyDetectionCVPR2018-Pytorch\pretrained\c3d.pickle --model_type c3d`

**Comment by RachanaAgarwal** [comment]
@ekosman 
The feature extractor is now working with the latest code changes in the master. Thanks for the update and support

**Comment by ekosman** [comment]
@RachanaAgarwal 
Great. May I close this?

**Comment by RachanaAgarwal** [comment]
@ekosman When I gave a list of videos(7-8 ranging from 2 to 15 mins ) for feature extraction in between I get below logs
followed by normal dumping features logs

WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
2200)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
2104)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
4424)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
495)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
4205)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
770)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
2460)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
4829)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
208)
torch.Size([0, 1, 1, 3]) x 16
2020-12-26 00:37:17,037 Video 35 / 9 : Writing clip 1130 of video break_4
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
4236)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
1568)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
3493)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
3744)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
697)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
3906)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
112)
torch.Size([0, 1, 1, 3]) x 16
WARNING:root:VideoIter:: ERROR (line number 75) !! (Force using another index:
20)
torch.Size([0, 1, 1, 3]) x 16

**Comment by ekosman** [comment]
@RachanaAgarwal 
Are all the video files valid?

**Comment by RachanaAgarwal** [comment]
Yes all the videos files are valid

**Comment by ekosman** [comment]
@RachanaAgarwal
Can you share the files? I want to see if I can reproduce this.

**Comment by RachanaAgarwal** [comment]
Sorry, can't share the video files. Please try with any long videos

**Comment by RachanaAgarwal** [comment]
@ekosman 
Getting below error when running TrainingAnomalyDetector_public.py.

 File "TrainingAnomalyDetector_public.py", line 96, in <module>
    save_every=20000)
  File "C:\old_laptop\paralaxiom\AnomalyDetectionCVPR2018-Pytorch-master\network\TorchUtils.py", line 118, in fit
    epoch=epoch)
  File "C:\old_laptop\paralaxiom\AnomalyDetectionCVPR2018-Pytorch-master\network\TorchUtils.py", line 177, in do_epoch
    batch = self.data_to_device(batch, self.device)
  File "C:\old_laptop\paralaxiom\AnomalyDetectionCVPR2018-Pytorch-master\network\TorchUtils.py", line 219, in data_to_device
    data = data.to(device)
AttributeError: 'str' object has no attribute 'to'



command
python TrainingAnomalyDetector_public.py --features_path anomaly_features --annotation_path Train_Annotation.txt

anomaly_features=> Directory having pre-computed features downloaded from https://drive.google.com/drive/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50?usp=sharing

**Comment by RachanaAgarwal** [comment]
@ekosman Any help to resolve the above issue is much appreciated

**Comment by ekosman** [comment]
@RachanaAgarwal I have some important deadlines soon so I won't be able to take care of it in the coming weeks. I'll keep this as a reminder anyway.

**Comment by seonghyun0108** [comment]
> @ekosman
> Getting below error when running TrainingAnomalyDetector_public.py.
> 
> File "TrainingAnomalyDetector_public.py", line 96, in
> save_every=20000)
> File "C:\AnomalyDetectionCVPR2018-Pytorch-master\network\TorchUtils.py", line 118, in fit
> epoch=epoch)
> File "C:\AnomalyDetectionCVPR2018-Pytorch-master\network\TorchUtils.py", line 177, in do_epoch
> batch = self.data_to_device(batch, self.device)
> File "C:\AnomalyDetectionCVPR2018-Pytorch-master\network\TorchUtils.py", line 219, in data_to_device
> data = data.to(device)
> AttributeError: 'str' object has no attribute 'to'
> 
> command
> python TrainingAnomalyDetector_public.py --features_path anomaly_features --annotation_path Train_Annotation.txt
> 
> anomaly_features=> Directory having pre-computed features downloaded from https://drive.google.com/drive/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50?usp=sharing

help me
