### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by huitailangdeerzi** [ekosman/AnomalyDetectionCVPR2018-Pytorch#61]
Traceback (most recent call last):
  File "TrainingAnomalyDetector_public.py", line 91, in <module>
    model.register_callback()
TypeError: register_callback() missing 1 required positional argument: 'callback_fn'

**Comment by NasikNafi** [comment]
@huitailangdeerzi You need to pass the `tb_writer` (which has been instantiated the line before) as an argument like the following:
`model.register_callback(tb_writer)`

**Comment by ekosman** [comment]
Fixed
