### ISSUE TITLE
Unexpected AUC value for modified testing dataset.

### ISSUE THREAD

**Issue by shekhor** [ekosman/AnomalyDetectionCVPR2018-Pytorch#63]
I have trained the model and getting almost the same result. However, for experimenting, I split the dataset into two parts and trained the model by one part of the dataset. Then in testing, I provided another part of datasets which I didn't provide in training. I am getting .73 AUC after 20k epochs, I was expecting a very lower AUC as I testing the model for totally new dataset. I am using precomputed features for training and testing. Can you please help me why I am getting this high AUC for an untrained test dataset? Thanks.

Training features:
![train_features](https://user-images.githubusercontent.com/18414273/106185358-f1a0c500-61cc-11eb-9838-0f53bef5d001.PNG)

Testing features:
![test_features](https://user-images.githubusercontent.com/18414273/106185395-fcf3f080-61cc-11eb-93e8-77eed16cb248.PNG)

**Comment by ekosman** [comment]
Can you elaborate on this? How do you split the dataset? Did you create new annotation files?
