### ISSUE TITLE
Different AUC after training for same epochs multiple times.

### ISSUE THREAD

**Issue by shekhor** [ekosman/AnomalyDetectionCVPR2018-Pytorch#64]
Hello,
If I train the model multiple times for the same number of epochs, I am getting different AUC like 1st time I got .55 AUC, then got .67, and then .49. Can anyone guide me, why I am getting such results? I trained the model for 100 epochs. Thanks.

**Comment by ekosman** [comment]
Hi @shekhor 

Training for such a small number of epochs is very unstable. You should train for at least 20K epochs as described in the original paper.
