### ISSUE TITLE
(Traning Issue) Callback doesn't fully implement the required interface 'float' object is not iterable

### ISSUE THREAD

**Issue by yx-chan131** [ekosman/AnomalyDetectionCVPR2018-Pytorch#69]
![callback](https://user-images.githubusercontent.com/68681893/108950250-dd9f9480-76a0-11eb-9f5d-8c3bb7a67580.PNG)
When I start training, those few lines in the picture keep appearing. The training process is still running. I would like to know what cause this problem and will it affect my training result?

**Comment by ekosman** [comment]
@yx-chan131 

I just pushed a patch for this. Would you mind checking if the error disapeared?

**Comment by yx-chan131** [comment]
Thanks! The error disappeared.
