### ISSUE TITLE
Video_demo.py not working

### ISSUE THREAD

**Issue by yx-chan131** [ekosman/AnomalyDetectionCVPR2018-Pytorch#71]
![video_demo not working](https://user-images.githubusercontent.com/68681893/109092661-ebf9b900-7751-11eb-8c45-5668bcad2c1c.PNG)

I use my own trained model which finished on epoch 800 to try testing on new videos, and the error occurs. I'm not sure which is the main cause to this problem. It would be nice if someone can explain why this happens to me. Some of the reasons I can think of right now are:
1. Maybe the epochs are still not enough. As I have read from some other issues, somebody said the model only worked when it is trained until epoch 20000. 
2. The saved model checkpoint extension is .pt while the pretrained model posted in repo is .weights.

**Comment by ekosman** [comment]
Hi @yx-chan131 

Thanks for reporting. I just patched this. Let me know if this has further problems.

**Comment by yx-chan131** [comment]
@ekosman Thanks! It is working just fine.
