### ISSUE TITLE
Training Loss Error

### ISSUE THREAD

**Issue by quanoo** [ekosman/AnomalyDetectionCVPR2018-Pytorch#73]
In TrainingAnomalyDetector_public.py, I had some problems. Could you help me?

In the "def get_args()"function, I set the epochs and models_dir initial value:
`parser.add_argument('--models_dir', type=str, default="exps/models")                    
parser.add_argument('--epochs', type=int, default=3) `
Because if I don't set the initial value of "epochs" and "model_dir", it doesn't seem to work. The path of "features_path" and "annotation_path" are both correct. And I didn't make any other changes to this file（TrainingAnomalyDetector_public.py）.
But when I run it, I have the following errors:

(adCVPR18) q@shy-imrs: ~/AnomalyDetectionCVPR2018-Pytorch$ python TrainingAnomalyDetector_public.py
2021-03-05 11:48:00,130 Training for 3 epochs
/home/q/AnomalyDetectionCVPR2018-Pytorch/network/anomaly_detector_model.py:36: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  normal_vids_indices = (y_true == 0).nonzero().flatten()
2021-03-05 11:48:02,943 Epoch 0/3      Iteration 0/1    loss: 1.0325759649276733    Time: 2.812 seconds/iteration
2021-03-05 11:48:02,943 Save the model after epoch 0
2021-03-05 11:48:02,961 
============================================================================================================================
Epoch 0/3     Train loss: 1.0325759649276733        time: 0:00:02.830652
============================================================================================================================

2021-03-05 11:48:05,723 Epoch 1/3      Iteration 0/1    loss: 1.0425223112106323    Time: 2.761 seconds/iteration
2021-03-05 11:48:05,723 
============================================================================================================================
Epoch 1/3     Train loss: 1.0425223112106323        time: 0:00:02.761791
============================================================================================================================

2021-03-05 11:48:08,512 Epoch 2/3      Iteration 0/1    loss: 1.0364242792129517    Time: 2.788 seconds/iteration
2021-03-05 11:48:08,512 
============================================================================================================================
Epoch 2/3     Train loss: 1.0364242792129517        time: 0:00:02.788565
============================================================================================================================

Traceback (most recent call last):
  File "TrainingAnomalyDetector_public.py", line 103, in <module>
    save_every=args.save_every)
  File "/home/q/AnomalyDetectionCVPR2018-Pytorch/network/TorchUtils.py", line 132, in fit
    self.notify_callbacks('on_training_end', self.model)
  File "/home/q/AnomalyDetectionCVPR2018-Pytorch/network/TorchUtils.py", line 85, in notify_callbacks
    method(*args, **kwargs)
  File "/home/q/AnomalyDetectionCVPR2018-Pytorch/utils/callbacks.py", line 80, in on_training_end
    plt.plot(range(1, self.epochs + 1), self.val_loss, label=f'Validation loss')
  File "/home/q/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2789, in plot
    is not None else {}), **kwargs)
  File "/home/q/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 1666, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/q/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 225, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/q/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 391, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/home/q/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 270, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (3,) and (0,)

First, I can only get " Train loss " but I could not get the  "Val loss", maybe that's why the X and Y dimensions are not consistent，but I don't know if my inference is correct.Could you help me to solve this "ValueError" problem?
Second, I want to ask that if I need to initialize the values for "eval_iter" and "evaluate_every" ?
In network\TorchUtils.py  def fit(self,
            train_iter,
            criterion,
            optimizer,
            eval_iter=None,
            epochs=10,
            network_model_path_base=None,
            save_every=None,
            evaluate_every=None,):

`val_loss = None
if eval_iter and evaluate_every and epoch % evaluate_every == 0:
    logging.info(f"Evaluating after epoch {epoch}")
    val_loss = self.evaluate(criterion=criterion,data_iter=eval_iter, )
self.notify_callbacks('on_training_iteration_end', train_loss, val_loss)`

Thank you for answering my question！

**Comment by ekosman** [comment]
@quanoo 
I just merged a patch. Let me know if this fixed the problem for you.

**Comment by quanoo** [comment]
I tried, but I got the same ValueError error.

**Comment by ekosman** [comment]
Hi @quanoo 

Please pull the code and try again. I tested it and it works just fine now + I uploaded new models that I finished training now for 100K epochs.

**Comment by quanoo** [comment]
I downloaded and ran it again, and it can run successfully this time. Thank you for helping me solve this problem. But I trained for 2W times, the result is not convergent, loss has been hovering at 1.04, excuse me is the number of training is not enough?
![2w_TrainLoss](https://user-images.githubusercontent.com/46098297/111580284-3bcc1d00-87f2-11eb-8469-6ad05533409c.png)

**Comment by ekosman** [comment]
@quanoo 

What auc value do you get?

**Comment by quanoo** [comment]
0.62

**Comment by ekosman** [comment]
Which features are you using? The pre-computed features or your own features?

**Comment by quanoo** [comment]
In TrainingAnomalyDetector_public.py
features_path=> Directory having pre-computed features downloaded from https://drive.google.com/drive/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50?usp=sharing
annotation_path=>Train_Annotation.txt

In generate_ROC.py
features_path=> Directory having pre-computed features downloaded from https://drive.google.com/drive/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50?usp=sharing
annotation_path=>Test_Annotation.txt
model_path=>epoch_20000.pt (PT file obtained after 2w TrainingAnomalyDetector_public.py training)
