### ISSUE TITLE
Lost Unique_Test_Annotation.txt file

### ISSUE THREAD

**Issue by CreateMiracle0523** [ekosman/AnomalyDetectionCVPR2018-Pytorch#8]
Thanks for the codes. I can't find the Unique_Test_Annotation.txt  in generate_ROC.py  Can you share the file to us ? 
`parser.add_argument('--annotation_path', default="Unique_Test_Annotation.txt",
                    help="path to annotations")`

**Comment by ekosman** [comment]
Use Test_Annotation.txt

**Comment by CreateMiracle0523** [comment]
I try Test_Annotation.txt to repalce Unqiue_Test_Annotation.txt. But I have some warning like this. Can you answer the problem to me ? Thanks a lot 
> Use Test_Annotation.txt
WARNING:root:VideoIter:: ERROR!! (Force using another index:
128)
Feature doesn't exist: out/Testing_Normal_Videos_Anomaly/Normal_Videos_015_x264.txt
WARNING:root:VideoIter:: ERROR!! (Force using another index:
128)
Feature doesn't exist: out/RoadAccidents/RoadAccidents019_x264.txt
WARNING:root:VideoIter:: ERROR!! (Force using another index:
53)
Feature doesn't exist: out/RoadAccidents/RoadAccidents019_x264.txt
WARNING:root:VideoIter:: ERROR!! (Force using another index:
38)
Feature doesn't exist: out/Shooting/Shooting010_x264.txt
WARNING:root:VideoIter:: ERROR!! (Force using another index:
244)
Feature doesn't exist: out/Testing_Normal_Videos_Anomaly/Normal_Videos_905_x264.txt
WARNING:root:VideoIter:: ERROR!! (Force using another index:
273)

**Comment by ekosman** [comment]
Please read the README file for the instruction how to run the script.
You probably don't provide the right path to the features
