### ISSUE TITLE
TypeError for video_demo.py

### ISSUE THREAD

**Issue by iaintSpaceMonkey** [ekosman/AnomalyDetectionCVPR2018-Pytorch#81]
I ran the demo with the command:
python video_demo.py --feature_extractor pretrained\c3d.pickle --feature_method c3d --ad_model exps\models\model_final_100000.weights --n_segments 2,
but get the _TypeError: 'collections.OrderedDict' object is not callable_ as the figure shows.
![TypeError](https://user-images.githubusercontent.com/17719168/113672766-b948c600-96ea-11eb-98d4-d579ace5035e.png)
Any help will be appreciated!

**Comment by ekosman** [comment]
@iaintSpaceMonkey 
Seems like you are using the old pretrained models. Try to use the models provided in `exps/models` in the master branch. Moreover, use `n_sgments 32` as mentioned in the original paper.

**Comment by iaintSpaceMonkey** [comment]
> @iaintSpaceMonkey
> Seems like you are using the old pretrained models. Try to use the models provided in `exps/models` in the master branch. Moreover, use `n_sgments 32` as mentioned in the original paper.

Oh, I see. Thanks for the reply!

**Comment by ekosman** [comment]
@iaintSpaceMonkey 
Let me know if this works for you, so I know if this issue can be closed.

**Comment by iaintSpaceMonkey** [comment]
> @iaintSpaceMonkey
> Let me know if this works for you, so I know if this issue can be closed.

It works for me, thanks!
