### ISSUE TITLE
Mean and std

### ISSUE THREAD

**Issue by iwillbethe** [ekosman/AnomalyDetectionCVPR2018-Pytorch#82]
When extractor features in c3d, Why should use mean and std like mean = [124 / 255, 117 / 255, 104 / 255]
        std = [1 / (.0167 * 255)] * 3. This is not like imagenet mean and std

**Comment by ekosman** [comment]
I used these statistics computed from the Kinetics dataset. Anyway, I consider training my own C3D model and recalculated this as well.
