### ISSUE TITLE
Help!! -- feature_extractor.py not executing

### ISSUE THREAD

**Issue by Yashrt263** [ekosman/AnomalyDetectionCVPR2018-Pytorch#85]
**[PLEASE HELP]**
I have cloned the environment to my anaconda. When i run the feature extractor using the command --> **python feature_extractor.py --dataset_path "path-to-dataset" --pretrained_3d "path-to-pretrained-fe"** -- it does not execute and throws the error -- **feature_extractor.py: error: the following arguments are required: --model_type** -- along with other feature extractor arguments listed.
What am I doing wrong? Please provide me with detailed execution procedure. Your advice would be of great help.
I have downloaded the dataset from the UCFCrime website.
![ghh](https://user-images.githubusercontent.com/86078569/122463694-89178080-cfd3-11eb-8908-35e773830793.PNG)

**Comment by ekosman** [comment]
As the message says, you should provide the required parameter to the script.

**Comment by Yashrt263** [comment]
@ekosman Thank You!! Its working now.
