### ISSUE TITLE
PLEASE HELP!! -- Permission Error [13]

### ISSUE THREAD

**Issue by Yashrt263** [ekosman/AnomalyDetectionCVPR2018-Pytorch#86]
**PLEASE HELP @ekosman **

I keep getting this permission error. I also got this error while executing the feature_extractor.ipynb on Jupyter Notebook.
Is this issue has something to do with the location of the project files? OR Have I made some mistake with the path I provided?
 
![kjkjj](https://user-images.githubusercontent.com/86078569/122468247-15787200-cfd9-11eb-822d-1b7033bf855d.PNG)

**Comment by ekosman** [comment]
Hi, I couldn't get into it over the weekend. Do you still need help?

**Comment by Yashrt263** [comment]
@ekosman No Sir, the issue was resolved. I will reach out to you if I run into any problems. Thanks!
