### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by nitincs** [ekosman/AnomalyDetectionCVPR2018-Pytorch#9]
solved

**Comment by libb999** [comment]
hello,can you tell the path of Features extraction
'path-to-dataset'
'path-to-train-annos'
'path-to-test-annos'
'path-to-pretrained-c3d'
also Training and Generate ROC curve
thank you

**Comment by ekosman** [comment]
@libb999 
dataset path - download the videos to your local drive from https://visionlab.uncc.edu/download/summary/60-data/477-ucf-anomaly-detection-dataset

annotations are provided in this repository and all other data is provided in README.

**Comment by libb999** [comment]
> @libb999
> dataset path - download the videos to your local drive from https://visionlab.uncc.edu/download/summary/60-data/477-ucf-anomaly-detection-dataset
> 
> annotations are provided in this repository and all other data is provided in README.

thank you very much！now i can see the ROC curve
next, i will train it and see the result
