### ISSUE TITLE
feature_extractor.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by ky-zhou** [ekosman/AnomalyDetectionCVPR2018-Pytorch#91]
I downloaded the data and stored it as the following style:

```
--data
----Abuse
----Arrest
....
----Normal_Videos_for_Event_recognition
....
----Stealing
----Testing_Normal_Videos_Anomaly
----Training_Normal_Videos_Anomaly
----Vandalism
```

and ran this commend: `python feature_extractor.py --dataset_path data --model_type c3d --pretrained_3d pretrained/c3d.pickle`

The data was downloaded from [the original implementation](https://github.com/WaqasSultani/AnomalyDetectionCVPR2018) . And the `c3d.pickle` was downloaded from: [the C3D link](https://github.com/DavideA/c3d-pytorch)
Then this error occured:

```
0it [00:00, ?it/s]
2021-06-29 22:27:28,497 Loading feature extractor from pretrained/c3d.pickle
Traceback (most recent call last):
  File "feature_extractor.py", line 204, in <module>
    main()
  File "feature_extractor.py", line 183, in main
    for data, clip_idxs, dirs, vid_names in data_iter:
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 62, in __iter__
    return iter(range(len(self.data_source)))
  File "/home/kj/Documents/AnomalyDetectionCVPR2018-Pytorch/data_loader.py", line 69, in __len__
    return len(self.video_clips)
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torchvision/datasets/video_utils.py", line 238, in __len__
    return self.num_clips()
  File "/home/kj/anaconda3/envs/adCVPR18/lib/python3.7/site-packages/torchvision/datasets/video_utils.py", line 247, in num_clips
    return self.cumulative_sizes[-1]
IndexError: list index out of range
```

Where am I doing wrong?

Besides this, can you also provide a description about how to use third-party data? Thank you.

**Comment by ekosman** [comment]
The `VideoClips` instance probably couldn't find any video file. Can you pull the current version of this repo and show me the output? Specifically this message:
`Found ... video files in ...`

**Comment by ky-zhou** [comment]
> The `VideoClips` instance probably couldn't find any video file. Can you pull the current version of this repo and show me the output? Specifically this message:
> `Found ... video files in ...`

Thanks for your reply. It is working now. The new data loader found all 1950 videos.
But writing clips for those videos is too slow. If I just need to detect some specific behaviors in the video, can I just use videos with those behaviors plus the normal videos? And will that cause overfitting in the following training phase?

**Comment by ekosman** [comment]
@ky-zhou Why not just use the pre-trained model?

**Comment by ky-zhou** [comment]
> @ky-zhou Why not just use the pre-trained model?

Because I am trying to increase the detection accuracy. New data could be added in the future.

**Comment by ekosman** [comment]
> 
> 
> > The `VideoClips` instance probably couldn't find any video file. Can you pull the current version of this repo and show me the output? Specifically this message:
> > `Found ... video files in ...`
> 
> Thanks for your reply. It is working now. The new data loader found all 1950 videos.
> But writing clips for those videos is too slow. If I just need to detect some specific behaviors in the video, can I just use videos with those behaviors plus the normal videos? And will that cause overfitting in the following training phase?

I can't guarantee a better detection accuracy. It'll probably overfit with not enough data.

**Comment by ky-zhou** [comment]
> > > The `VideoClips` instance probably couldn't find any video file. Can you pull the current version of this repo and show me the output? Specifically this message:
> > > `Found ... video files in ...`
> > 
> > 
> > Thanks for your reply. It is working now. The new data loader found all 1950 videos.
> > But writing clips for those videos is too slow. If I just need to detect some specific behaviors in the video, can I just use videos with those behaviors plus the normal videos? And will that cause overfitting in the following training phase?
> 
> I can't guarantee a better detection accuracy. It'll probably overfit with not enough data. You can discuss it with the original author of the paper, maybe he has some insights regarding training with fewer data.

Yes, thanks for your advise. Great discussion here. Issue will be closed.
