### ISSUE TITLE
Sequence of execution of the following steps

### ISSUE THREAD

**Issue by anbuharry** [ekosman/AnomalyDetectionCVPR2018-Pytorch#93]
Hai @ekosman 

Can you elaborate on the steps to run the project and dependencies needed , How to Run Demo file can anyone share example to run demo file

`python video_demo.py --feature_extractor "path-to-pretrained-fe" --feature_method "fe-method" --ad_model "path-to-pretrained-ad-model" --n_segments "number-of-segments"`

Thank you

**Comment by ekosman** [comment]
Hi @anbuharry 

In order to run `video_demo` you all you need is pretty much run the aforementioned command and pass the corresponding arguments. For example:

```
python video_demo.py --feature_extractor pretrained/c3d.pickle --feature_method c3d --ad_model exps/models/epoch_20000.py --n_segments 32
```

**Comment by anbuharry** [comment]
hai 

![error](https://user-images.githubusercontent.com/54160097/126869268-e349ffb9-1fc8-44d4-badb-a03f89e931b0.png)

Can you explain why this error happens ? how to solve it

**Comment by ekosman** [comment]
The first warning will be removed by running the script with a different value for 'num_workers', e.g. '--num_workers 2'.

The second warning originates from torchvision and can be ignored.

**Comment by anbuharry** [comment]
`python TrainingAnomalyDetector_public.py --features_path "path-to-dataset" --annotation_path "path-to-train-annos"`

Here what is anotation path?

Thanks for your reply

**Comment by ekosman** [comment]
The path to `Train_Annotations.txt` supplied in this repository.

**Comment by anbuharry** [comment]
> The path to `Train_Annotations.txt` supplied in this repository.

Thank you so much

**Comment by Chuttyboy** [comment]
> Hi @anbuharry
> 
> In order to run `video_demo` you all you need is pretty much run the aforementioned command and pass the corresponding arguments. For example:
> 
> ```
> python video_demo.py --feature_extractor pretrained/c3d.pickle --feature_method c3d --ad_model exps/models/epoch_20000.py --n_segments 32
> ```
Hello @ekosman  

Given sample is correct because i got error when i tried

**Comment by ekosman** [comment]
@Chuttyboy 
It should be included in the environment file, but you can try to install PyQT5 via:
```
pip install PyQt5
```

Additionally, note that the extension of `ad_model` should be `pt` instead of `py`.

**Comment by Chuttyboy** [comment]
> Hi @anbuharry
> 
> In order to run `video_demo` you all you need is pretty much run the aforementioned command and pass the corresponding arguments. For example:
> 
> ```
> python video_demo.py --feature_extractor pretrained/c3d.pickle --feature_method c3d --ad_model exps/models/epoch_20000.pt --n_segments 32
> ```
Hello @ekosman 

Could you please give examples for both feature extraction and training, Path to a dataset it  cofusion whether I it was pre-computed fe or dataset which one i give that's why i ask you

**Comment by ekosman** [comment]
@Chuttyboy 

I added more documentation to the `README.md` file. Please let me know if there's anything unclear.

**Comment by Chuttyboy** [comment]
> @Chuttyboy
> 
> I added more documentation to the `README.md` file. Please let me know if there's anything unclear.

I face an error while extracting feature (illegal instruction (core dumped)

**Comment by ekosman** [comment]
@Chuttyboy 

Can you elaborate on this? What is the command you have tried to run?

**Comment by anbuharry** [comment]
> @Chuttyboy
> 
> Can you elaborate on this? What is the command you have tried to run?

Hi @ekosman 
Feature Extraction :
`python feature_extractor.py --dataset_path data --model_type c3d --pretrained_3d pretrained/c3d.pickle`

Refused Feature Extraction download Pre computed features download through link in Read me and i stored features in anomaly features

Training :
`python TrainingAnomalyDetector_public.py --features_path anomaly_features --annotation_path Train_Annotation.txt`

anomaly_features - Pre computed feature 
Annotation path is Train_annotation.txt path

**Comment by Chuttyboy** [comment]
> @Chuttyboy
> 
> Can you elaborate on this? What is the command you have tried to run?

@ekosman 

While Ran Demo file Everything works well but in pop up, screen video didn't play
