### ISSUE TITLE
Core dumped Error

### ISSUE THREAD

**Issue by anbuharry** [ekosman/AnomalyDetectionCVPR2018-Pytorch#94]
Hai, 

![error1](https://user-images.githubusercontent.com/54160097/126943896-6f7dea36-9493-4726-892b-7315e64edde1.png)

Can anyone explain why this error happens and how to resolve it 

Thank you

**Comment by anbuharry** [comment]
> Hai,
> 
> ![error1](https://user-images.githubusercontent.com/54160097/126943896-6f7dea36-9493-4726-892b-7315e64edde1.png)
> 
> Can anyone explain why this error happens and how to resolve it
> 
> Thank you

Sorry, I forgot to activate anaconda environment that why this error happened

**Comment by anbuharry** [comment]
![error2](https://user-images.githubusercontent.com/54160097/126950852-a1f2ab1b-fc6f-4d1f-8439-fb3d2aabbd51.png)

Why did this error happen? how to resolved it

**Comment by ekosman** [comment]
Hi @anbuharry 

Have you downloaded the video dataset and extracted the features, or alternatively downloaded the pre computed features as described in the `README.md` file?
