### ISSUE TITLE
Training & Genrate ROC curve

### ISSUE THREAD

**Issue by Chuttyboy** [ekosman/AnomalyDetectionCVPR2018-Pytorch#95]
Hai @ekosman 

`python TrainingAnomalyDetector_public.py --features_path "path-to-dataset" --annotation_path "path-to-train-annos"`

`python generate_ROC.py --features_path "path-to-dataset" --annotation_path "path-to-annos" --model_path "path-to-model"`

Can anyone explain how the training process works and give Example for above mentioned comment 

Thank you

**Comment by ekosman** [comment]
Hello @Chuttyboy 

Thanks for your question, I'll add more information about these arguments in the `README.md` file.

Meanwhile:
* `path-to-dataset` is the path to the directory containing the pre-computed features
* `annotation_path` is the path to the annotations file (`.txt` extension. `Train_annotations.txt` for training, `Test_annotations.txt` for testing.
* `model_path` is the path to the trained anomaly detection model (you can download a pre-trained model from `exps/models`.

Hope this helps.

**Comment by Chuttyboy** [comment]
Hai @ekosman 

`ModuleNotFoundError: No module named 'PyQt5.QtMultimedia'`

While running Demo File I got this error how can I overcome this issue?

**Comment by ekosman** [comment]
Can you copy and paste the full error log?

**Comment by Chuttyboy** [comment]
> Can you copy and paste the full error log?

[Same Error I too face](https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/94#issue-952558289)

**Comment by ekosman** [comment]
> issue 2:
> ![core_dump](https://user-images.githubusercontent.com/79959547/127139458-c23eb607-7951-436b-a2b6-a7f24b621d2d.png)
> 
> This issue happens even extracting all 1950 videos
> 

I'll try to reproduce this error. Meanwhile, can you show me that command you are trying to run?


> Issue 3: Training
> 
> In this part, I use pre-computed features
> 
> `python TrainingAnomalyDetector_public.py --features_path feature --annotation_path ./Videos/Anomaly-Pytorch/Train_Annotation.txt`
> 
> ```
> `Feature doesn't exist: feat/Training_Normal_Videos_Anomaly/Normal_Videos535_x264.txt
> 2021-07-27 15:33:43,694 VideoIter:: ERROR!! (Force using another index:
> 4189)
> 
> Feature doesn't exist: feat/Training_Normal_Videos_Anomaly/Normal_Videos386_x264.txt
> 2021-07-27 15:33:43,700 VideoIter:: ERROR!! (Force using another index:
> 8872)`
> ```

It is strange, because you pass `feature` as an argument and then the loader tries to load features from a directory called `feat`... What the the name of the directory which contains all the computed features for the UCF dataset?

**Comment by Chuttyboy** [comment]
Hai @ekosman 

I downloaded pre-computed features as per the readme file and that issue was resolved but after running any command ( Feature extraction, Training, demo ) I faced illegal instruction (core dumped ) error

How to resolved it?

Thank you

**Comment by ekosman** [comment]
Sorry, This error does not reproduce on my machine.
