### ISSUE TITLE
issues in Training

### ISSUE THREAD

**Issue by anbuharry** [ekosman/AnomalyDetectionCVPR2018-Pytorch#96]
Hai @ekosman 
```
2021-07-27 21:58:46,246 Training for 2 epochs
2021-07-27 21:58:46,360 VideoIter:: ERROR!! (Force using another index:
6910)
Feature doesn't exist: /home/vinsent/Music/AnomalyDetectionCVPR2018-Pytorch/features/Training_Normal_Videos_Anomaly/Normal_Videos110_x264.txt
2021-07-27 21:58:46,366 VideoIter:: ERROR!! (Force using another index:
3702)
Feature doesn't exist: /home/vinsent/Music/AnomalyDetectionCVPR2018-Pytorch/features/Training_Normal_Videos_Anomaly/Normal_Videos652_x264.txt
2021-07-27 21:58:46,375 VideoIter:: ERROR!! (Force using another index:
16990)
```
My Train : 

`python TrainingAnomalyDetector_public.py --features_path /home/vinsent/Videos/Anomaly-Pytorch/dataz --annotation_path Train_Annotation.txt`

Data'z has pre-computed extracted feature

Train_Annotation.txt  - path given (Not Empty)

Then why above mentioned message pops and how to start training properly with precomputed features

**Comment by ekosman** [comment]
@anbuharry Can you show me what does `dataz` contain?

**Comment by anbuharry** [comment]
> @anbuharry Can you show me what does `dataz` contain?

![dataz](https://user-images.githubusercontent.com/54160097/127201191-0630b368-07b6-4f19-b9df-b7369771059f.png)

**Comment by ekosman** [comment]
@anbuharry 
It looks like the names of the directories don't match. For example, `Training-Normal-Videos-P...` is not a valid name. Where did you download those features from?

**Comment by anbuharry** [comment]
> @anbuharry
> It looks like the names of the directories don't match the annotations. For example, `Training-Normal-Videos-P...` is not a valid name. Where did you download those features from?

[Here](https://www.dropbox.com/sh/75v5ehq4cdg5g5g/AABvnJSwZI7zXb8_myBA0CLHa?dl=0)

**Comment by ekosman** [comment]
@anbuharry 

The training script expects a path to the directory containing features of videos, not the video themselves. You can download them from https://drive.google.com/drive/u/1/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50

Alternatively, you can extract the features from the videos you have already downloaded.

**Comment by anbuharry** [comment]
> @anbuharry
> 
> The training script expects a path to the directory containing features of videos, not the video themselves. You can download them from https://drive.google.com/drive/u/1/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50
> 
> Alternatively, you can extract the features from the videos you have already downloaded.

@ekosman 
Could you please give example to run a training file

**Comment by ekosman** [comment]
@anbuharry Sure.

First, download the pre-computed features from the link I provided above to google drive.

Say the path to the downloaded features is `anomaly_features`. Then, run the following commands:
```
cd AnomalyDetectionCVPR2018-Pytorch
python TrainingAnomalyDetector_public.py --features_path anomaly_features --annotation_path Train_Annotation.txt
```

That should work.

**Comment by anbuharry** [comment]
> @anbuharry Sure.
> 
> First, download the pre-computed features from the link I provided above to google drive.
> 
> Say the path to the downloaded features is `anomaly_features`. Then, run the following commands:
> 
> ```
> cd AnomalyDetectionCVPR2018-Pytorch
> python TrainingAnomalyDetector_public.py --features_path anomaly_features --annotation_path Train_Annotation.txt
> ```
> 
> That should work.

@ekosman 

`2021-07-26 12:33:08,495 Training for 2 epochs
2021-07-26 12:33:08,579 VideoIter:: ERROR!! (Force using another index:
15895)
Feature doesn't exist: /home/vinsent/Videos/AnomalyDetectionCVPR2018-Pytorch/data/Training_Normal_Videos_Anomaly/Normal_Videos578_x264.txt
2021-07-26 12:33:08,582 VideoIter:: ERROR!! (Force using another index:
1364)`

I got this when run above given comment

**Comment by ekosman** [comment]
@anbuharry 
Have you downloaded the features from the google drive link?

**Comment by anbuharry** [comment]
> @anbuharry
> Have you downloaded the features from the google drive link?
@ekosman 

Yes I download features through the link given by you

**Comment by ekosman** [comment]
@anbuharry 
Can you show me the content of the directory where you have downloaded this?

**Comment by anbuharry** [comment]
@ekosman 

![Screenshot from 2021-07-28 00-00-35](https://user-images.githubusercontent.com/54160097/127208479-cc53b410-6713-4e9b-b8fc-60f493b0a3f4.png)
[Anomaly_feature](https://drive.google.com/drive/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50)

**Comment by ekosman** [comment]
@anbuharry 
I conclude that the path provided to the script as an argument for the path of the feature is incorrect. The above message says that the it couldn't find the feature `Training_Normal_Videos_Anomaly/Normal_Videos578_x264.txt` in the directory `/home/vinsent/Videos/AnomalyDetectionCVPR2018-Pytorch/data`. However, it seems like you have downloaded the features somewhere else. I suggest you find the right path where you have downloaded the features and provide this as an argument for `features_path` to the training script

**Comment by anbuharry** [comment]
> @anbuharry
> I conclude that the path provided to the script as an argument for the path of the feature is incorrect. The above message says that it couldn't find the feature `Training_Normal_Videos_Anomaly/Normal_Videos578_x264.txt` in the directory `/home/vinsent/Videos/AnomalyDetectionCVPR2018-Pytorch/data`. However, it seems like you have downloaded the features somewhere else. I suggest you find the right path where you have downloaded the features and provide this as an argument for `features_path` to the training script

@ekosman 

Ok i will try to do that thank you so much glad to talk with you keep in touch

**Comment by anbuharry** [comment]
@ekosman

![Uploading train.png…]()

The given path is correct or not

**Comment by Chuttyboy** [comment]
![demoerror](https://user-images.githubusercontent.com/79959547/127360245-b1bd14b8-4542-4292-8247-0377ff3d5e77.png)

Explain this error in this part I just activate env and run the demo with pre-trained model I got an error

`python video_demo.py --feature_extractor pretrained/c3d.pickle --feature_method c3d --ad_model exps/models/epoch_20000.pt --n_segments 32`

**Comment by anbuharry** [comment]
Hello @ekosman 

![assert](https://user-images.githubusercontent.com/54160097/127508693-04518a8c-6069-4751-8af8-f73d87ce22e0.png)

Why this issue occur and how to solve this

**Comment by anbuharry** [comment]
hai @ekosman 
```
Traceback (most recent call last):
  File "video_demo.py", line 10, in <module>
    import pyqtgraph as pg
  File "/home/vinsent/anaconda3/envs/anomaly/lib/python3.7/site-packages/pyqtgraph/__init__.py", line 13, in <module>
    from .Qt import QtCore, QtGui, mkQApp
  File "/home/vinsent/anaconda3/envs/anomaly/lib/python3.7/site-packages/pyqtgraph/Qt/__init__.py", line 158, in <module>
    from PyQt5 import QtSvg
ValueError: PyCapsule_GetPointer called with incorrect name`
```

Help me out from this .....

**Comment by ekosman** [comment]
> ValueError: PyCapsule_GetPointer called with incorrect name`

Try this:
https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe

**Comment by anbuharry** [comment]
> > ValueError: PyCapsule_GetPointer called with incorrect name`
> 
> Try this:
> https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe

No still i get the same error

**Comment by ekosman** [comment]
> Hai @ekosman
> 
> > > ValueError: PyCapsule_GetPointer called with incorrect name`
> > 
> > 
> > Try this:
> > https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe
> 
> No still i get the same error , One more error i metioned here
> 
> `python TrainingAnomalyDetector_public.py --features_path features --annotation_path Train_Annotation.txt`
> 
> while run this command i got
> 
> ```
> `2021-07-29 21:15:52,507 Training for 2 epochs
> 
> Illegal instruction (core dumped)`
> ```
> 
> #this error

Sorry, this error does not reproduce on my machine.

**Comment by anbuharry** [comment]
> > Hai @ekosman
> > > > ValueError: PyCapsule_GetPointer called with incorrect name`
> > > 
> > > 
> > > Try this:
> > > https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe
> > 
> > 
> > No still i get the same error , One more error i metioned here
> > `python TrainingAnomalyDetector_public.py --features_path features --annotation_path Train_Annotation.txt`
> > while run this command i got
> > ```
> > `2021-07-29 21:15:52,507 Training for 2 epochs
> > 
> > Illegal instruction (core dumped)`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #this error
> 
> Sorry, This error does not reproduce on my machine and other machines I checked.

After run demo file video not shown only graph appears

**Comment by anbuharry** [comment]
Hai @ekosman 

![dgusa](https://user-images.githubusercontent.com/54160097/127533854-a11e4bce-e14b-4ca8-b832-4918ac657284.png)

**Comment by ekosman** [comment]
> Hai @ekosman
> 
> ![dgusa](https://user-images.githubusercontent.com/54160097/127533854-a11e4bce-e14b-4ca8-b832-4918ac657284.png)

As this error does not reproduce on my machine, I can't provide a straight answer but a quick search on Google leads here:

https://stackoverflow.com/questions/26099139/how-to-fix-gstreamer-error-in-qt5

**Comment by Chuttyboy** [comment]
@ekosman 

![van](https://user-images.githubusercontent.com/79959547/128178452-138e2b21-7c3d-4963-8e86-f747371d89db.png)

How to overcome this issue

Thankyou
